/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QTimeEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QTreeView>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QTableWidget *tableWidget;
    QTableWidget *tableWidget_2;
    QComboBox *comboBox;
    QComboBox *comboBox_2;
    QComboBox *comboBox_3;
    QComboBox *comboBox_4;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLineEdit *lineEdit;
    QLabel *label_5;
    QLabel *label_6;
    QComboBox *comboBox_5;
    QPushButton *pushButton_4;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_61;
    QWidget *tab_2;
    QComboBox *departmentBox;
    QLabel *label_15;
    QTableWidget *universityTable;
    QComboBox *collegeBox;
    QPushButton *addCollege;
    QPushButton *editUnoversity;
    QPushButton *removeUniversity;
    QLabel *label_13;
    QLabel *label_14;
    QComboBox *majorBox;
    QLabel *label_16;
    QComboBox *courseBox;
    QLabel *label_17;
    QComboBox *sectionsBox;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QLabel *label_27;
    QLabel *label_28;
    QPushButton *pushButton_19;
    QLineEdit *lineEdit_11;
    QWidget *page_2;
    QLabel *label_29;
    QLabel *label_30;
    QComboBox *comboBox_13;
    QLabel *label_31;
    QPushButton *pushButton_20;
    QLabel *label_36;
    QComboBox *comboBox_16;
    QLineEdit *lineEdit_2;
    QWidget *page_3;
    QLabel *label_32;
    QLabel *label_33;
    QComboBox *comboBox_14;
    QLabel *label_34;
    QComboBox *comboBox_15;
    QLabel *label_35;
    QPushButton *pushButton_21;
    QLineEdit *lineEdit_3;
    QWidget *page_4;
    QLabel *label_37;
    QLabel *label_38;
    QComboBox *comboBox_17;
    QLabel *label_39;
    QComboBox *comboBox_18;
    QLabel *label_40;
    QComboBox *comboBox_19;
    QLabel *label_41;
    QPushButton *pushButton_22;
    QLineEdit *lineEdit_4;
    QWidget *page_5;
    QLabel *label_42;
    QLabel *label_43;
    QComboBox *comboBox_20;
    QLabel *label_44;
    QComboBox *comboBox_21;
    QLabel *label_45;
    QComboBox *comboBox_22;
    QLabel *label_46;
    QComboBox *comboBox_23;
    QLabel *label_47;
    QLabel *label_48;
    QComboBox *comboBox_24;
    QPushButton *pushButton_23;
    QLabel *label_54;
    QTimeEdit *timeEdit;
    QLabel *label_55;
    QTimeEdit *timeEdit_2;
    QLabel *label_56;
    QLabel *label_57;
    QComboBox *comboBox_28;
    QLabel *label_62;
    QComboBox *comboBox_31;
    QLabel *label_63;
    QComboBox *comboBox_32;
    QLineEdit *lineEdit_9;
    QLineEdit *lineEdit_10;
    QWidget *page_6;
    QPushButton *pushButton_15;
    QPushButton *addMajor;
    QPushButton *addCourse;
    QPushButton *addSection;
    QLabel *label_52;
    QComboBox *yearBox;
    QLabel *label_53;
    QComboBox *semesterBox;
    QWidget *tab_9;
    QLabel *label_18;
    QTableWidget *employeeTable;
    QPushButton *addEmployee;
    QPushButton *editEmployee;
    QPushButton *deleteEmployee;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_49;
    QLabel *label_51;
    QPushButton *employeeSave;
    QLineEdit *EmployeeFirstName;
    QLineEdit *employeeLastName;
    QLineEdit *employeeMI;
    QLineEdit *employeeSalary;
    QWidget *tab_10;
    QTreeView *treeView;
    QLabel *label_11;
    QComboBox *comboBox_11;
    QLabel *label_12;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QLabel *label_21;
    QTextEdit *textEdit_3;
    QLabel *label_22;
    QLabel *label_23;
    QSpinBox *spinBox;
    QPushButton *pushButton_13;
    QLabel *label_24;
    QLabel *label_25;
    QComboBox *comboBox_12;
    QLabel *label_26;
    QTextEdit *textEdit_4;
    QPushButton *pushButton_14;
    QLabel *label_69;
    QSpinBox *spinBox_2;
    QPushButton *pushButton_25;
    QWidget *tab_3;
    QLineEdit *studentIDentered;
    QLabel *label_64;
    QPushButton *pushButton_27;
    QPushButton *pushButton_28;
    QPushButton *deleteStudent;
    QTableView *tableView_2;
    QPushButton *pushButton_31;
    QWidget *widget_2;
    QLabel *label_65;
    QLineEdit *lineEdit_6;
    QLabel *label_220;
    QLineEdit *lineEdit_7;
    QLabel *label_230;
    QLineEdit *lineEdit_8;
    QLabel *label_66;
    QPushButton *pushButton_30;
    QWidget *widget;
    QLabel *label_160;
    QComboBox *comboBox_80;
    QLabel *label_161;
    QRadioButton *radioButton;
    QRadioButton *radioButton_2;
    QLabel *label_70;
    QRadioButton *radioButton_3;
    QRadioButton *radioButton_4;
    QWidget *widget_3;
    QLabel *label_67;
    QLabel *label_68;
    QComboBox *comboBox_29;
    QLabel *label_200;
    QComboBox *comboBox_30;
    QPushButton *pushButton_26;
    QWidget *tab_5;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QTableView *tableView;
    QPushButton *pushButton_32;
    QWidget *widget_4;
    QLabel *label_58;
    QTextEdit *textEdit_12;
    QLabel *label_59;
    QPushButton *pushButton;
    QLabel *label_60;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1028, 715);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(20, 20, 1011, 621));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        tableWidget = new QTableWidget(tab);
        tableWidget->setObjectName(QString::fromUtf8("tableWidget"));
        tableWidget->setGeometry(QRect(455, 241, 441, 211));
        tableWidget_2 = new QTableWidget(tab);
        tableWidget_2->setObjectName(QString::fromUtf8("tableWidget_2"));
        tableWidget_2->setGeometry(QRect(10, 10, 231, 391));
        comboBox = new QComboBox(tab);
        comboBox->setObjectName(QString::fromUtf8("comboBox"));
        comboBox->setGeometry(QRect(250, 30, 72, 22));
        comboBox_2 = new QComboBox(tab);
        comboBox_2->setObjectName(QString::fromUtf8("comboBox_2"));
        comboBox_2->setGeometry(QRect(250, 80, 72, 22));
        comboBox_3 = new QComboBox(tab);
        comboBox_3->setObjectName(QString::fromUtf8("comboBox_3"));
        comboBox_3->setGeometry(QRect(250, 130, 72, 22));
        comboBox_4 = new QComboBox(tab);
        comboBox_4->setObjectName(QString::fromUtf8("comboBox_4"));
        comboBox_4->setGeometry(QRect(250, 180, 72, 22));
        label = new QLabel(tab);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(250, 10, 71, 16));
        label_2 = new QLabel(tab);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(250, 60, 71, 16));
        label_3 = new QLabel(tab);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(250, 110, 71, 16));
        label_4 = new QLabel(tab);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(250, 160, 71, 16));
        lineEdit = new QLineEdit(tab);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(250, 240, 113, 21));
        label_5 = new QLabel(tab);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(250, 220, 71, 16));
        label_6 = new QLabel(tab);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(250, 270, 91, 16));
        comboBox_5 = new QComboBox(tab);
        comboBox_5->setObjectName(QString::fromUtf8("comboBox_5"));
        comboBox_5->setGeometry(QRect(250, 290, 111, 22));
        pushButton_4 = new QPushButton(tab);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(370, 290, 80, 31));
        label_7 = new QLabel(tab);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(460, 220, 111, 16));
        label_8 = new QLabel(tab);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(470, 20, 71, 16));
        label_9 = new QLabel(tab);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(470, 100, 71, 16));
        label_10 = new QLabel(tab);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(470, 60, 91, 16));
        label_61 = new QLabel(tab);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(480, 140, 71, 16));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        departmentBox = new QComboBox(tab_2);
        departmentBox->setObjectName(QString::fromUtf8("departmentBox"));
        departmentBox->setGeometry(QRect(250, 100, 171, 22));
        label_15 = new QLabel(tab_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(250, 10, 71, 16));
        universityTable = new QTableWidget(tab_2);
        universityTable->setObjectName(QString::fromUtf8("universityTable"));
        universityTable->setGeometry(QRect(10, 10, 231, 471));
        collegeBox = new QComboBox(tab_2);
        collegeBox->setObjectName(QString::fromUtf8("collegeBox"));
        collegeBox->setGeometry(QRect(250, 30, 171, 22));
        addCollege = new QPushButton(tab_2);
        addCollege->setObjectName(QString::fromUtf8("addCollege"));
        addCollege->setGeometry(QRect(430, 20, 51, 31));
        editUnoversity = new QPushButton(tab_2);
        editUnoversity->setObjectName(QString::fromUtf8("editUnoversity"));
        editUnoversity->setGeometry(QRect(20, 500, 51, 31));
        removeUniversity = new QPushButton(tab_2);
        removeUniversity->setObjectName(QString::fromUtf8("removeUniversity"));
        removeUniversity->setGeometry(QRect(80, 500, 81, 31));
        label_13 = new QLabel(tab_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(250, 70, 91, 16));
        label_14 = new QLabel(tab_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(250, 140, 59, 16));
        majorBox = new QComboBox(tab_2);
        majorBox->setObjectName(QString::fromUtf8("majorBox"));
        majorBox->setGeometry(QRect(250, 160, 171, 32));
        label_16 = new QLabel(tab_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(250, 210, 59, 16));
        courseBox = new QComboBox(tab_2);
        courseBox->setObjectName(QString::fromUtf8("courseBox"));
        courseBox->setGeometry(QRect(250, 230, 171, 32));
        label_17 = new QLabel(tab_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(250, 290, 59, 16));
        sectionsBox = new QComboBox(tab_2);
        sectionsBox->setObjectName(QString::fromUtf8("sectionsBox"));
        sectionsBox->setGeometry(QRect(250, 320, 171, 32));
        stackedWidget = new QStackedWidget(tab_2);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setEnabled(true);
        stackedWidget->setGeometry(QRect(510, 30, 481, 551));
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        label_27 = new QLabel(page);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(100, 10, 131, 16));
        label_28 = new QLabel(page);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(40, 50, 91, 16));
        pushButton_19 = new QPushButton(page);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(70, 220, 91, 31));
        lineEdit_11 = new QLineEdit(page);
        lineEdit_11->setObjectName(QString::fromUtf8("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(40, 70, 171, 21));
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        page_2->setEnabled(true);
        label_29 = new QLabel(page_2);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(100, 20, 141, 16));
        label_30 = new QLabel(page_2);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(50, 70, 71, 16));
        comboBox_13 = new QComboBox(page_2);
        comboBox_13->setObjectName(QString::fromUtf8("comboBox_13"));
        comboBox_13->setGeometry(QRect(60, 100, 171, 22));
        label_31 = new QLabel(page_2);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(50, 150, 131, 16));
        pushButton_20 = new QPushButton(page_2);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(110, 350, 91, 31));
        label_36 = new QLabel(page_2);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(50, 220, 131, 16));
        comboBox_16 = new QComboBox(page_2);
        comboBox_16->setObjectName(QString::fromUtf8("comboBox_16"));
        comboBox_16->setGeometry(QRect(60, 250, 171, 22));
        lineEdit_2 = new QLineEdit(page_2);
        lineEdit_2->setObjectName(QString::fromUtf8("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(70, 180, 171, 21));
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        label_32 = new QLabel(page_3);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(110, 30, 141, 16));
        label_33 = new QLabel(page_3);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(70, 80, 71, 16));
        comboBox_14 = new QComboBox(page_3);
        comboBox_14->setObjectName(QString::fromUtf8("comboBox_14"));
        comboBox_14->setGeometry(QRect(80, 110, 171, 22));
        label_34 = new QLabel(page_3);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(70, 150, 91, 16));
        comboBox_15 = new QComboBox(page_3);
        comboBox_15->setObjectName(QString::fromUtf8("comboBox_15"));
        comboBox_15->setGeometry(QRect(80, 190, 171, 22));
        label_35 = new QLabel(page_3);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(80, 240, 111, 16));
        pushButton_21 = new QPushButton(page_3);
        pushButton_21->setObjectName(QString::fromUtf8("pushButton_21"));
        pushButton_21->setGeometry(QRect(130, 310, 91, 31));
        lineEdit_3 = new QLineEdit(page_3);
        lineEdit_3->setObjectName(QString::fromUtf8("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(110, 270, 171, 21));
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QString::fromUtf8("page_4"));
        label_37 = new QLabel(page_4);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(120, 30, 141, 16));
        label_38 = new QLabel(page_4);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(40, 80, 71, 16));
        comboBox_17 = new QComboBox(page_4);
        comboBox_17->setObjectName(QString::fromUtf8("comboBox_17"));
        comboBox_17->setGeometry(QRect(50, 100, 171, 22));
        label_39 = new QLabel(page_4);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(40, 150, 91, 16));
        comboBox_18 = new QComboBox(page_4);
        comboBox_18->setObjectName(QString::fromUtf8("comboBox_18"));
        comboBox_18->setGeometry(QRect(50, 170, 171, 22));
        label_40 = new QLabel(page_4);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(50, 210, 59, 16));
        comboBox_19 = new QComboBox(page_4);
        comboBox_19->setObjectName(QString::fromUtf8("comboBox_19"));
        comboBox_19->setGeometry(QRect(50, 230, 171, 32));
        label_41 = new QLabel(page_4);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(50, 280, 91, 16));
        pushButton_22 = new QPushButton(page_4);
        pushButton_22->setObjectName(QString::fromUtf8("pushButton_22"));
        pushButton_22->setGeometry(QRect(120, 360, 91, 31));
        lineEdit_4 = new QLineEdit(page_4);
        lineEdit_4->setObjectName(QString::fromUtf8("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(60, 310, 171, 21));
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QString::fromUtf8("page_5"));
        label_42 = new QLabel(page_5);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(110, 20, 141, 16));
        label_43 = new QLabel(page_5);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(40, 60, 71, 16));
        comboBox_20 = new QComboBox(page_5);
        comboBox_20->setObjectName(QString::fromUtf8("comboBox_20"));
        comboBox_20->setGeometry(QRect(30, 80, 171, 22));
        label_44 = new QLabel(page_5);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(40, 120, 91, 16));
        comboBox_21 = new QComboBox(page_5);
        comboBox_21->setObjectName(QString::fromUtf8("comboBox_21"));
        comboBox_21->setGeometry(QRect(30, 150, 171, 22));
        label_45 = new QLabel(page_5);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(40, 190, 59, 16));
        comboBox_22 = new QComboBox(page_5);
        comboBox_22->setObjectName(QString::fromUtf8("comboBox_22"));
        comboBox_22->setGeometry(QRect(30, 210, 171, 32));
        label_46 = new QLabel(page_5);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(30, 250, 59, 16));
        comboBox_23 = new QComboBox(page_5);
        comboBox_23->setObjectName(QString::fromUtf8("comboBox_23"));
        comboBox_23->setGeometry(QRect(30, 270, 171, 32));
        label_47 = new QLabel(page_5);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(30, 330, 59, 16));
        label_48 = new QLabel(page_5);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(30, 400, 91, 16));
        comboBox_24 = new QComboBox(page_5);
        comboBox_24->setObjectName(QString::fromUtf8("comboBox_24"));
        comboBox_24->setGeometry(QRect(20, 420, 171, 32));
        pushButton_23 = new QPushButton(page_5);
        pushButton_23->setObjectName(QString::fromUtf8("pushButton_23"));
        pushButton_23->setGeometry(QRect(40, 520, 91, 31));
        label_54 = new QLabel(page_5);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(280, 60, 71, 16));
        timeEdit = new QTimeEdit(page_5);
        timeEdit->setObjectName(QString::fromUtf8("timeEdit"));
        timeEdit->setGeometry(QRect(280, 80, 118, 22));
        label_55 = new QLabel(page_5);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(280, 120, 71, 16));
        timeEdit_2 = new QTimeEdit(page_5);
        timeEdit_2->setObjectName(QString::fromUtf8("timeEdit_2"));
        timeEdit_2->setGeometry(QRect(280, 140, 118, 22));
        label_56 = new QLabel(page_5);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(280, 190, 59, 16));
        label_57 = new QLabel(page_5);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(280, 280, 81, 16));
        comboBox_28 = new QComboBox(page_5);
        comboBox_28->setObjectName(QString::fromUtf8("comboBox_28"));
        comboBox_28->setGeometry(QRect(280, 300, 91, 32));
        label_62 = new QLabel(page_5);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(280, 380, 61, 16));
        comboBox_31 = new QComboBox(page_5);
        comboBox_31->setObjectName(QString::fromUtf8("comboBox_31"));
        comboBox_31->setGeometry(QRect(250, 400, 221, 32));
        label_63 = new QLabel(page_5);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(260, 460, 59, 16));
        comboBox_32 = new QComboBox(page_5);
        comboBox_32->setObjectName(QString::fromUtf8("comboBox_32"));
        comboBox_32->setGeometry(QRect(250, 480, 221, 32));
        lineEdit_9 = new QLineEdit(page_5);
        lineEdit_9->setObjectName(QString::fromUtf8("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(280, 220, 171, 21));
        lineEdit_10 = new QLineEdit(page_5);
        lineEdit_10->setObjectName(QString::fromUtf8("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(30, 360, 101, 21));
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QString::fromUtf8("page_6"));
        stackedWidget->addWidget(page_6);
        pushButton_15 = new QPushButton(tab_2);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(430, 100, 51, 31));
        addMajor = new QPushButton(tab_2);
        addMajor->setObjectName(QString::fromUtf8("addMajor"));
        addMajor->setGeometry(QRect(430, 160, 51, 31));
        addCourse = new QPushButton(tab_2);
        addCourse->setObjectName(QString::fromUtf8("addCourse"));
        addCourse->setGeometry(QRect(430, 230, 51, 31));
        addSection = new QPushButton(tab_2);
        addSection->setObjectName(QString::fromUtf8("addSection"));
        addSection->setGeometry(QRect(430, 320, 51, 31));
        label_52 = new QLabel(tab_2);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(250, 370, 59, 16));
        yearBox = new QComboBox(tab_2);
        yearBox->setObjectName(QString::fromUtf8("yearBox"));
        yearBox->setGeometry(QRect(250, 390, 91, 32));
        label_53 = new QLabel(tab_2);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(260, 430, 81, 16));
        semesterBox = new QComboBox(tab_2);
        semesterBox->setObjectName(QString::fromUtf8("semesterBox"));
        semesterBox->setGeometry(QRect(250, 450, 91, 32));
        tabWidget->addTab(tab_2, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QString::fromUtf8("tab_9"));
        label_18 = new QLabel(tab_9);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(40, 20, 141, 16));
        employeeTable = new QTableWidget(tab_9);
        employeeTable->setObjectName(QString::fromUtf8("employeeTable"));
        employeeTable->setGeometry(QRect(40, 50, 256, 192));
        addEmployee = new QPushButton(tab_9);
        addEmployee->setObjectName(QString::fromUtf8("addEmployee"));
        addEmployee->setGeometry(QRect(40, 260, 81, 32));
        editEmployee = new QPushButton(tab_9);
        editEmployee->setObjectName(QString::fromUtf8("editEmployee"));
        editEmployee->setGeometry(QRect(130, 260, 71, 32));
        deleteEmployee = new QPushButton(tab_9);
        deleteEmployee->setObjectName(QString::fromUtf8("deleteEmployee"));
        deleteEmployee->setGeometry(QRect(200, 260, 91, 32));
        label_19 = new QLabel(tab_9);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(410, 40, 91, 16));
        label_20 = new QLabel(tab_9);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(410, 110, 81, 16));
        label_49 = new QLabel(tab_9);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(410, 170, 81, 16));
        label_51 = new QLabel(tab_9);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(410, 250, 81, 16));
        employeeSave = new QPushButton(tab_9);
        employeeSave->setObjectName(QString::fromUtf8("employeeSave"));
        employeeSave->setGeometry(QRect(690, 280, 91, 32));
        EmployeeFirstName = new QLineEdit(tab_9);
        EmployeeFirstName->setObjectName(QString::fromUtf8("EmployeeFirstName"));
        EmployeeFirstName->setGeometry(QRect(410, 60, 171, 21));
        employeeLastName = new QLineEdit(tab_9);
        employeeLastName->setObjectName(QString::fromUtf8("employeeLastName"));
        employeeLastName->setGeometry(QRect(410, 140, 171, 21));
        employeeMI = new QLineEdit(tab_9);
        employeeMI->setObjectName(QString::fromUtf8("employeeMI"));
        employeeMI->setGeometry(QRect(410, 200, 171, 21));
        employeeSalary = new QLineEdit(tab_9);
        employeeSalary->setObjectName(QString::fromUtf8("employeeSalary"));
        employeeSalary->setGeometry(QRect(410, 280, 171, 21));
        tabWidget->addTab(tab_9, QString());
        tab_10 = new QWidget();
        tab_10->setObjectName(QString::fromUtf8("tab_10"));
        treeView = new QTreeView(tab_10);
        treeView->setObjectName(QString::fromUtf8("treeView"));
        treeView->setGeometry(QRect(10, 50, 256, 192));
        label_11 = new QLabel(tab_10);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(270, 50, 201, 16));
        comboBox_11 = new QComboBox(tab_10);
        comboBox_11->setObjectName(QString::fromUtf8("comboBox_11"));
        comboBox_11->setGeometry(QRect(300, 80, 171, 32));
        label_12 = new QLabel(tab_10);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 290, 121, 31));
        label_12->setFrameShadow(QFrame::Raised);
        label_12->setTextFormat(Qt::AutoText);
        label_12->setWordWrap(true);
        label_12->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        pushButton_11 = new QPushButton(tab_10);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(530, 30, 81, 32));
        pushButton_12 = new QPushButton(tab_10);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(610, 30, 81, 32));
        label_21 = new QLabel(tab_10);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(10, 20, 59, 16));
        textEdit_3 = new QTextEdit(tab_10);
        textEdit_3->setObjectName(QString::fromUtf8("textEdit_3"));
        textEdit_3->setGeometry(QRect(30, 360, 151, 21));
        label_22 = new QLabel(tab_10);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(30, 330, 101, 16));
        label_23 = new QLabel(tab_10);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(30, 400, 91, 16));
        spinBox = new QSpinBox(tab_10);
        spinBox->setObjectName(QString::fromUtf8("spinBox"));
        spinBox->setGeometry(QRect(30, 420, 91, 22));
        pushButton_13 = new QPushButton(tab_10);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(20, 470, 113, 32));
        label_24 = new QLabel(tab_10);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(380, 290, 111, 16));
        label_25 = new QLabel(tab_10);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(410, 320, 61, 16));
        comboBox_12 = new QComboBox(tab_10);
        comboBox_12->setObjectName(QString::fromUtf8("comboBox_12"));
        comboBox_12->setGeometry(QRect(410, 340, 221, 32));
        label_26 = new QLabel(tab_10);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(410, 390, 59, 16));
        textEdit_4 = new QTextEdit(tab_10);
        textEdit_4->setObjectName(QString::fromUtf8("textEdit_4"));
        textEdit_4->setGeometry(QRect(420, 410, 81, 21));
        pushButton_14 = new QPushButton(tab_10);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(410, 510, 113, 32));
        label_69 = new QLabel(tab_10);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(420, 450, 131, 16));
        spinBox_2 = new QSpinBox(tab_10);
        spinBox_2->setObjectName(QString::fromUtf8("spinBox_2"));
        spinBox_2->setGeometry(QRect(420, 470, 91, 22));
        pushButton_25 = new QPushButton(tab_10);
        pushButton_25->setObjectName(QString::fromUtf8("pushButton_25"));
        pushButton_25->setGeometry(QRect(690, 30, 81, 32));
        tabWidget->addTab(tab_10, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        studentIDentered = new QLineEdit(tab_3);
        studentIDentered->setObjectName(QString::fromUtf8("studentIDentered"));
        studentIDentered->setGeometry(QRect(250, 30, 113, 21));
        label_64 = new QLabel(tab_3);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(250, 10, 131, 16));
        pushButton_27 = new QPushButton(tab_3);
        pushButton_27->setObjectName(QString::fromUtf8("pushButton_27"));
        pushButton_27->setGeometry(QRect(360, 30, 81, 31));
        pushButton_28 = new QPushButton(tab_3);
        pushButton_28->setObjectName(QString::fromUtf8("pushButton_28"));
        pushButton_28->setGeometry(QRect(250, 70, 113, 31));
        deleteStudent = new QPushButton(tab_3);
        deleteStudent->setObjectName(QString::fromUtf8("deleteStudent"));
        deleteStudent->setGeometry(QRect(250, 100, 113, 31));
        tableView_2 = new QTableView(tab_3);
        tableView_2->setObjectName(QString::fromUtf8("tableView_2"));
        tableView_2->setGeometry(QRect(10, 20, 231, 391));
        pushButton_31 = new QPushButton(tab_3);
        pushButton_31->setObjectName(QString::fromUtf8("pushButton_31"));
        pushButton_31->setGeometry(QRect(250, 140, 113, 31));
        widget_2 = new QWidget(tab_3);
        widget_2->setObjectName(QString::fromUtf8("widget_2"));
        widget_2->setGeometry(QRect(470, 20, 451, 501));
        label_65 = new QLabel(widget_2);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(0, 10, 141, 16));
        lineEdit_6 = new QLineEdit(widget_2);
        lineEdit_6->setObjectName(QString::fromUtf8("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(130, 10, 201, 21));
        label_220 = new QLabel(widget_2);
        label_220->setObjectName(QString::fromUtf8("label_220"));
        label_220->setGeometry(QRect(0, 40, 131, 16));
        lineEdit_7 = new QLineEdit(widget_2);
        lineEdit_7->setObjectName(QString::fromUtf8("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(130, 40, 201, 21));
        label_230 = new QLabel(widget_2);
        label_230->setObjectName(QString::fromUtf8("label_230"));
        label_230->setGeometry(QRect(0, 70, 81, 16));
        lineEdit_8 = new QLineEdit(widget_2);
        lineEdit_8->setObjectName(QString::fromUtf8("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(80, 70, 61, 21));
        label_66 = new QLabel(widget_2);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(0, 110, 81, 16));
        pushButton_30 = new QPushButton(widget_2);
        pushButton_30->setObjectName(QString::fromUtf8("pushButton_30"));
        pushButton_30->setGeometry(QRect(310, 160, 113, 31));
        widget = new QWidget(widget_2);
        widget->setObjectName(QString::fromUtf8("widget"));
        widget->setEnabled(true);
        widget->setGeometry(QRect(-10, 200, 461, 161));
        widget->setAutoFillBackground(false);
        label_160 = new QLabel(widget);
        label_160->setObjectName(QString::fromUtf8("label_160"));
        label_160->setGeometry(QRect(10, 10, 251, 16));
        comboBox_80 = new QComboBox(widget);
        comboBox_80->setObjectName(QString::fromUtf8("comboBox_80"));
        comboBox_80->setGeometry(QRect(10, 30, 161, 22));
        label_161 = new QLabel(widget);
        label_161->setObjectName(QString::fromUtf8("label_161"));
        label_161->setGeometry(QRect(30, 120, 91, 16));
        radioButton = new QRadioButton(widget);
        radioButton->setObjectName(QString::fromUtf8("radioButton"));
        radioButton->setGeometry(QRect(130, 120, 63, 16));
        radioButton_2 = new QRadioButton(widget);
        radioButton_2->setObjectName(QString::fromUtf8("radioButton_2"));
        radioButton_2->setGeometry(QRect(220, 120, 63, 16));
        label_70 = new QLabel(widget_2);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(10, 170, 81, 16));
        radioButton_3 = new QRadioButton(widget_2);
        radioButton_3->setObjectName(QString::fromUtf8("radioButton_3"));
        radioButton_3->setGeometry(QRect(90, 170, 100, 20));
        radioButton_4 = new QRadioButton(widget_2);
        radioButton_4->setObjectName(QString::fromUtf8("radioButton_4"));
        radioButton_4->setGeometry(QRect(140, 170, 100, 20));
        widget_3 = new QWidget(tab_3);
        widget_3->setObjectName(QString::fromUtf8("widget_3"));
        widget_3->setGeometry(QRect(470, 380, 451, 191));
        label_67 = new QLabel(widget_3);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(0, 10, 371, 16));
        label_68 = new QLabel(widget_3);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(10, 40, 51, 16));
        comboBox_29 = new QComboBox(widget_3);
        comboBox_29->setObjectName(QString::fromUtf8("comboBox_29"));
        comboBox_29->setGeometry(QRect(10, 60, 161, 22));
        label_200 = new QLabel(widget_3);
        label_200->setObjectName(QString::fromUtf8("label_200"));
        label_200->setGeometry(QRect(200, 40, 91, 16));
        comboBox_30 = new QComboBox(widget_3);
        comboBox_30->setObjectName(QString::fromUtf8("comboBox_30"));
        comboBox_30->setGeometry(QRect(240, 60, 91, 22));
        pushButton_26 = new QPushButton(widget_3);
        pushButton_26->setObjectName(QString::fromUtf8("pushButton_26"));
        pushButton_26->setGeometry(QRect(280, 110, 141, 31));
        tabWidget->addTab(tab_3, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        pushButton_2 = new QPushButton(tab_5);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(330, 430, 141, 31));
        pushButton_3 = new QPushButton(tab_5);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(190, 430, 121, 31));
        tableView = new QTableView(tab_5);
        tableView->setObjectName(QString::fromUtf8("tableView"));
        tableView->setGeometry(QRect(10, 10, 471, 401));
        pushButton_32 = new QPushButton(tab_5);
        pushButton_32->setObjectName(QString::fromUtf8("pushButton_32"));
        pushButton_32->setGeometry(QRect(40, 430, 121, 31));
        widget_4 = new QWidget(tab_5);
        widget_4->setObjectName(QString::fromUtf8("widget_4"));
        widget_4->setGeometry(QRect(540, 30, 361, 191));
        label_58 = new QLabel(widget_4);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(10, 30, 71, 16));
        textEdit_12 = new QTextEdit(widget_4);
        textEdit_12->setObjectName(QString::fromUtf8("textEdit_12"));
        textEdit_12->setGeometry(QRect(100, 30, 181, 21));
        label_59 = new QLabel(widget_4);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(10, 80, 71, 16));
        pushButton = new QPushButton(widget_4);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(110, 150, 131, 31));
        label_60 = new QLabel(widget_4);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(80, 80, 59, 16));
        tabWidget->addTab(tab_5, QString());
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1028, 22));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(3);
        stackedWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        label->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Major:", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Course:", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "Add Class", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "Remove Class", nullptr));
        pushButton_4->setText(QApplication::translate("MainWindow", "Remove", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "Current Schedule:", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "First Name:", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "Last Name:", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "Middle Initial:", nullptr));
        label_61->setText(QApplication::translate("MainWindow", "AdminID:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Student", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "College:", nullptr));
        addCollege->setText(QApplication::translate("MainWindow", "Add", nullptr));
        editUnoversity->setText(QApplication::translate("MainWindow", "Edit", nullptr));
        removeUniversity->setText(QApplication::translate("MainWindow", "Remove", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "Major", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "Course", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "Sections", nullptr));
        label_27->setText(QApplication::translate("MainWindow", "Add or Edit College", nullptr));
        label_28->setText(QApplication::translate("MainWindow", "College Name:", nullptr));
        pushButton_19->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_29->setText(QApplication::translate("MainWindow", "Add or Edit Department", nullptr));
        label_30->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_31->setText(QApplication::translate("MainWindow", "Department Name:", nullptr));
        pushButton_20->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_36->setText(QApplication::translate("MainWindow", "Department Chair:", nullptr));
        label_32->setText(QApplication::translate("MainWindow", "Add or Edit Major", nullptr));
        label_33->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_34->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_35->setText(QApplication::translate("MainWindow", "Major Name:", nullptr));
        pushButton_21->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_37->setText(QApplication::translate("MainWindow", "Add or Edit Course", nullptr));
        label_38->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_39->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_40->setText(QApplication::translate("MainWindow", "Major", nullptr));
        label_41->setText(QApplication::translate("MainWindow", "Course Name:", nullptr));
        pushButton_22->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_42->setText(QApplication::translate("MainWindow", "Add or Edit Section", nullptr));
        label_43->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_44->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_45->setText(QApplication::translate("MainWindow", "Major:", nullptr));
        label_46->setText(QApplication::translate("MainWindow", "Course:", nullptr));
        label_47->setText(QApplication::translate("MainWindow", "Section #:", nullptr));
        label_48->setText(QApplication::translate("MainWindow", "Professor:", nullptr));
        pushButton_23->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_54->setText(QApplication::translate("MainWindow", "Start Time:", nullptr));
        label_55->setText(QApplication::translate("MainWindow", "End Time:", nullptr));
        label_56->setText(QApplication::translate("MainWindow", "Year:", nullptr));
        label_57->setText(QApplication::translate("MainWindow", "Semester:", nullptr));
        label_62->setText(QApplication::translate("MainWindow", "Building:", nullptr));
        label_63->setText(QApplication::translate("MainWindow", "Room #:", nullptr));
        pushButton_15->setText(QApplication::translate("MainWindow", "Add", nullptr));
        addMajor->setText(QApplication::translate("MainWindow", "Add", nullptr));
        addCourse->setText(QApplication::translate("MainWindow", "Add", nullptr));
        addSection->setText(QApplication::translate("MainWindow", "Add", nullptr));
        label_52->setText(QApplication::translate("MainWindow", "Year:", nullptr));
        label_53->setText(QApplication::translate("MainWindow", "Semester:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "University", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "Employee List:", nullptr));
        addEmployee->setText(QApplication::translate("MainWindow", "Add", nullptr));
        editEmployee->setText(QApplication::translate("MainWindow", "Edit", nullptr));
        deleteEmployee->setText(QApplication::translate("MainWindow", "Delete", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "First Name", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "Last Name", nullptr));
        label_49->setText(QApplication::translate("MainWindow", "MI:", nullptr));
        label_51->setText(QApplication::translate("MainWindow", "Salary:", nullptr));
        employeeSave->setText(QApplication::translate("MainWindow", "Save", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_9), QApplication::translate("MainWindow", "Employees", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "Select a Building to see Rooms", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "Add/Edit Building", nullptr));
        pushButton_11->setText(QApplication::translate("MainWindow", "Delete", nullptr));
        pushButton_12->setText(QApplication::translate("MainWindow", "Edit", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "Rooms:", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "Building Name:", nullptr));
        label_23->setText(QApplication::translate("MainWindow", "Rooms inside", nullptr));
        pushButton_13->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_24->setText(QApplication::translate("MainWindow", "Add/Edit Room", nullptr));
        label_25->setText(QApplication::translate("MainWindow", "Building:", nullptr));
        label_26->setText(QApplication::translate("MainWindow", "Room #:", nullptr));
        pushButton_14->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_69->setText(QApplication::translate("MainWindow", "Room Occupency:", nullptr));
        pushButton_25->setText(QApplication::translate("MainWindow", "Add", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_10), QApplication::translate("MainWindow", "Rooms", nullptr));
        label_64->setText(QApplication::translate("MainWindow", "Find Student by ID:", nullptr));
        pushButton_27->setText(QApplication::translate("MainWindow", "Enter", nullptr));
        pushButton_28->setText(QApplication::translate("MainWindow", "Edit/View", nullptr));
        deleteStudent->setText(QApplication::translate("MainWindow", "Delete", nullptr));
        pushButton_31->setText(QApplication::translate("MainWindow", "Add Student", nullptr));
        label_65->setText(QApplication::translate("MainWindow", "Student First Name:", nullptr));
        label_220->setText(QApplication::translate("MainWindow", "Student Last Name:", nullptr));
        label_230->setText(QApplication::translate("MainWindow", "Student MI:", nullptr));
        label_66->setText(QApplication::translate("MainWindow", "Student ID:", nullptr));
        pushButton_30->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_160->setText(QApplication::translate("MainWindow", "Pick Semester you want to view:", nullptr));
        label_161->setText(QApplication::translate("MainWindow", "Paid Tuition:", nullptr));
        radioButton->setText(QApplication::translate("MainWindow", "Yes", nullptr));
        radioButton_2->setText(QApplication::translate("MainWindow", "No", nullptr));
        label_70->setText(QApplication::translate("MainWindow", "Registered?", nullptr));
        radioButton_3->setText(QApplication::translate("MainWindow", "yes", nullptr));
        radioButton_4->setText(QApplication::translate("MainWindow", "no", nullptr));
        label_67->setText(QApplication::translate("MainWindow", "Edit Student Grade for a Course in Semester picked above:", nullptr));
        label_68->setText(QApplication::translate("MainWindow", "Course: ", nullptr));
        label_200->setText(QApplication::translate("MainWindow", "New Grade:", nullptr));
        pushButton_26->setText(QApplication::translate("MainWindow", "Save", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "Admin", nullptr));
        pushButton_2->setText(QApplication::translate("MainWindow", "Delete Admin", nullptr));
        pushButton_3->setText(QApplication::translate("MainWindow", "Edit Admin", nullptr));
        pushButton_32->setText(QApplication::translate("MainWindow", "Add Admin", nullptr));
        label_58->setText(QApplication::translate("MainWindow", "Password:", nullptr));
        label_59->setText(QApplication::translate("MainWindow", "AdminID:", nullptr));
        pushButton->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_60->setText(QApplication::translate("MainWindow", "ID#", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("MainWindow", "Super Admin", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
