/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QTreeView>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QTableWidget *tableWidget;
    QTableWidget *tableWidget_2;
    QComboBox *comboBox;
    QComboBox *comboBox_2;
    QComboBox *comboBox_3;
    QComboBox *comboBox_4;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLineEdit *lineEdit;
    QLabel *label_5;
    QLabel *label_6;
    QComboBox *comboBox_5;
    QPushButton *pushButton_4;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QWidget *tab_2;
    QComboBox *comboBox_7;
    QLabel *label_15;
    QTableWidget *tableWidget_3;
    QComboBox *comboBox_9;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QLabel *label_13;
    QLabel *label_14;
    QComboBox *comboBox_6;
    QLabel *label_16;
    QComboBox *comboBox_8;
    QLabel *label_17;
    QComboBox *comboBox_10;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QLabel *label_27;
    QLabel *label_28;
    QTextEdit *textEdit_5;
    QPushButton *pushButton_19;
    QWidget *page_2;
    QLabel *label_29;
    QLabel *label_30;
    QComboBox *comboBox_13;
    QLabel *label_31;
    QPlainTextEdit *plainTextEdit;
    QPushButton *pushButton_20;
    QLabel *label_36;
    QComboBox *comboBox_16;
    QWidget *page_3;
    QLabel *label_32;
    QLabel *label_33;
    QComboBox *comboBox_14;
    QLabel *label_34;
    QComboBox *comboBox_15;
    QLabel *label_35;
    QTextEdit *textEdit_6;
    QPushButton *pushButton_21;
    QWidget *page_4;
    QLabel *label_37;
    QLabel *label_38;
    QComboBox *comboBox_17;
    QLabel *label_39;
    QComboBox *comboBox_18;
    QLabel *label_40;
    QComboBox *comboBox_19;
    QLabel *label_41;
    QTextEdit *textEdit_7;
    QPushButton *pushButton_22;
    QWidget *page_5;
    QLabel *label_42;
    QLabel *label_43;
    QComboBox *comboBox_20;
    QLabel *label_44;
    QComboBox *comboBox_21;
    QLabel *label_45;
    QComboBox *comboBox_22;
    QLabel *label_46;
    QComboBox *comboBox_23;
    QLabel *label_47;
    QTextEdit *textEdit_8;
    QLabel *label_48;
    QComboBox *comboBox_24;
    QPushButton *pushButton_23;
    QPushButton *pushButton_15;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QWidget *tab_9;
    QLabel *label_18;
    QTableWidget *tableWidget_4;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QLabel *label_19;
    QTextEdit *textEdit;
    QLabel *label_20;
    QTextEdit *textEdit_2;
    QLabel *label_49;
    QTextEdit *textEdit_9;
    QLabel *label_50;
    QComboBox *comboBox_25;
    QTextEdit *textEdit_10;
    QLabel *label_51;
    QWidget *tab_10;
    QTreeView *treeView;
    QLabel *label_11;
    QComboBox *comboBox_11;
    QLabel *label_12;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QLabel *label_21;
    QTextEdit *textEdit_3;
    QLabel *label_22;
    QLabel *label_23;
    QSpinBox *spinBox;
    QPushButton *pushButton_13;
    QLabel *label_24;
    QLabel *label_25;
    QComboBox *comboBox_12;
    QLabel *label_26;
    QTextEdit *textEdit_4;
    QPushButton *pushButton_14;
    QWidget *tab_3;
    QTableWidget *tableWidget_41;
    QLabel *label_131;
    QLabel *label_141;
    QRadioButton *radioButton;
    QRadioButton *radioButton_2;
    QLabel *label_161;
    QComboBox *comboBox_81;
    QLabel *label_171;
    QLabel *label_181;
    QLabel *label_191;
    QComboBox *comboBox_101;
    QLabel *label_201;
    QComboBox *comboBox_111;
    QLineEdit *lineEdit_2;
    QLabel *label_211;
    QLabel *label_221;
    QLineEdit *lineEdit_3;
    QLabel *label_231;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_5;
    QPushButton *pushButton_81;
    QLabel *label_241;
    QLineEdit *lineEdit_6;
    QPushButton *pushButton_91;
    QPushButton *pushButton_101;
    QWidget *tab_5;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QTableView *tableView;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1028, 715);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(20, 30, 971, 601));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        tableWidget = new QTableWidget(tab);
        tableWidget->setObjectName(QString::fromUtf8("tableWidget"));
        tableWidget->setGeometry(QRect(455, 241, 291, 161));
        tableWidget_2 = new QTableWidget(tab);
        tableWidget_2->setObjectName(QString::fromUtf8("tableWidget_2"));
        tableWidget_2->setGeometry(QRect(10, 10, 231, 391));
        comboBox = new QComboBox(tab);
        comboBox->setObjectName(QString::fromUtf8("comboBox"));
        comboBox->setGeometry(QRect(250, 30, 72, 22));
        comboBox_2 = new QComboBox(tab);
        comboBox_2->setObjectName(QString::fromUtf8("comboBox_2"));
        comboBox_2->setGeometry(QRect(250, 80, 72, 22));
        comboBox_3 = new QComboBox(tab);
        comboBox_3->setObjectName(QString::fromUtf8("comboBox_3"));
        comboBox_3->setGeometry(QRect(250, 130, 72, 22));
        comboBox_4 = new QComboBox(tab);
        comboBox_4->setObjectName(QString::fromUtf8("comboBox_4"));
        comboBox_4->setGeometry(QRect(250, 180, 72, 22));
        label = new QLabel(tab);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(250, 10, 71, 16));
        label_2 = new QLabel(tab);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(250, 60, 71, 16));
        label_3 = new QLabel(tab);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(250, 110, 71, 16));
        label_4 = new QLabel(tab);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(250, 160, 71, 16));
        lineEdit = new QLineEdit(tab);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(250, 240, 113, 21));
        label_5 = new QLabel(tab);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(250, 220, 71, 16));
        label_6 = new QLabel(tab);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(250, 270, 91, 16));
        comboBox_5 = new QComboBox(tab);
        comboBox_5->setObjectName(QString::fromUtf8("comboBox_5"));
        comboBox_5->setGeometry(QRect(250, 290, 111, 22));
        pushButton_4 = new QPushButton(tab);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(370, 290, 80, 31));
        label_7 = new QLabel(tab);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(460, 220, 111, 16));
        label_8 = new QLabel(tab);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(470, 20, 71, 16));
        label_9 = new QLabel(tab);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(470, 100, 71, 16));
        label_10 = new QLabel(tab);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(470, 60, 91, 16));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        comboBox_7 = new QComboBox(tab_2);
        comboBox_7->setObjectName(QString::fromUtf8("comboBox_7"));
        comboBox_7->setGeometry(QRect(250, 100, 171, 22));
        label_15 = new QLabel(tab_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(250, 10, 71, 16));
        tableWidget_3 = new QTableWidget(tab_2);
        tableWidget_3->setObjectName(QString::fromUtf8("tableWidget_3"));
        tableWidget_3->setGeometry(QRect(10, 10, 231, 391));
        comboBox_9 = new QComboBox(tab_2);
        comboBox_9->setObjectName(QString::fromUtf8("comboBox_9"));
        comboBox_9->setGeometry(QRect(250, 30, 171, 22));
        pushButton_5 = new QPushButton(tab_2);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(430, 20, 51, 31));
        pushButton_6 = new QPushButton(tab_2);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(10, 410, 51, 31));
        pushButton_7 = new QPushButton(tab_2);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(80, 410, 81, 31));
        label_13 = new QLabel(tab_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(250, 70, 91, 16));
        label_14 = new QLabel(tab_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(250, 140, 59, 16));
        comboBox_6 = new QComboBox(tab_2);
        comboBox_6->setObjectName(QString::fromUtf8("comboBox_6"));
        comboBox_6->setGeometry(QRect(250, 160, 171, 32));
        label_16 = new QLabel(tab_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(250, 210, 59, 16));
        comboBox_8 = new QComboBox(tab_2);
        comboBox_8->setObjectName(QString::fromUtf8("comboBox_8"));
        comboBox_8->setGeometry(QRect(250, 230, 171, 32));
        label_17 = new QLabel(tab_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(250, 290, 59, 16));
        comboBox_10 = new QComboBox(tab_2);
        comboBox_10->setObjectName(QString::fromUtf8("comboBox_10"));
        comboBox_10->setGeometry(QRect(250, 320, 171, 32));
        stackedWidget = new QStackedWidget(tab_2);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(540, 20, 351, 551));
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        label_27 = new QLabel(page);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(100, 10, 131, 16));
        label_28 = new QLabel(page);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(40, 50, 91, 16));
        textEdit_5 = new QTextEdit(page);
        textEdit_5->setObjectName(QString::fromUtf8("textEdit_5"));
        textEdit_5->setGeometry(QRect(40, 70, 141, 21));
        pushButton_19 = new QPushButton(page);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(70, 130, 91, 31));
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        label_29 = new QLabel(page_2);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(100, 20, 141, 16));
        label_30 = new QLabel(page_2);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(50, 70, 71, 16));
        comboBox_13 = new QComboBox(page_2);
        comboBox_13->setObjectName(QString::fromUtf8("comboBox_13"));
        comboBox_13->setGeometry(QRect(60, 100, 171, 22));
        label_31 = new QLabel(page_2);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(50, 150, 131, 16));
        plainTextEdit = new QPlainTextEdit(page_2);
        plainTextEdit->setObjectName(QString::fromUtf8("plainTextEdit"));
        plainTextEdit->setGeometry(QRect(70, 170, 171, 21));
        pushButton_20 = new QPushButton(page_2);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(110, 350, 91, 31));
        label_36 = new QLabel(page_2);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(50, 220, 131, 16));
        comboBox_16 = new QComboBox(page_2);
        comboBox_16->setObjectName(QString::fromUtf8("comboBox_16"));
        comboBox_16->setGeometry(QRect(60, 250, 171, 22));
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        label_32 = new QLabel(page_3);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(110, 30, 141, 16));
        label_33 = new QLabel(page_3);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(70, 80, 71, 16));
        comboBox_14 = new QComboBox(page_3);
        comboBox_14->setObjectName(QString::fromUtf8("comboBox_14"));
        comboBox_14->setGeometry(QRect(80, 110, 171, 22));
        label_34 = new QLabel(page_3);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(70, 150, 91, 16));
        comboBox_15 = new QComboBox(page_3);
        comboBox_15->setObjectName(QString::fromUtf8("comboBox_15"));
        comboBox_15->setGeometry(QRect(80, 190, 171, 22));
        label_35 = new QLabel(page_3);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(80, 240, 111, 16));
        textEdit_6 = new QTextEdit(page_3);
        textEdit_6->setObjectName(QString::fromUtf8("textEdit_6"));
        textEdit_6->setGeometry(QRect(90, 270, 171, 21));
        pushButton_21 = new QPushButton(page_3);
        pushButton_21->setObjectName(QString::fromUtf8("pushButton_21"));
        pushButton_21->setGeometry(QRect(130, 310, 91, 31));
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QString::fromUtf8("page_4"));
        label_37 = new QLabel(page_4);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(120, 30, 141, 16));
        label_38 = new QLabel(page_4);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(40, 80, 71, 16));
        comboBox_17 = new QComboBox(page_4);
        comboBox_17->setObjectName(QString::fromUtf8("comboBox_17"));
        comboBox_17->setGeometry(QRect(50, 100, 171, 22));
        label_39 = new QLabel(page_4);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(40, 150, 91, 16));
        comboBox_18 = new QComboBox(page_4);
        comboBox_18->setObjectName(QString::fromUtf8("comboBox_18"));
        comboBox_18->setGeometry(QRect(50, 170, 171, 22));
        label_40 = new QLabel(page_4);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(50, 210, 59, 16));
        comboBox_19 = new QComboBox(page_4);
        comboBox_19->setObjectName(QString::fromUtf8("comboBox_19"));
        comboBox_19->setGeometry(QRect(50, 230, 171, 32));
        label_41 = new QLabel(page_4);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(50, 280, 91, 16));
        textEdit_7 = new QTextEdit(page_4);
        textEdit_7->setObjectName(QString::fromUtf8("textEdit_7"));
        textEdit_7->setGeometry(QRect(70, 300, 181, 21));
        pushButton_22 = new QPushButton(page_4);
        pushButton_22->setObjectName(QString::fromUtf8("pushButton_22"));
        pushButton_22->setGeometry(QRect(120, 360, 91, 31));
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QString::fromUtf8("page_5"));
        label_42 = new QLabel(page_5);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(110, 20, 141, 16));
        label_43 = new QLabel(page_5);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(40, 60, 71, 16));
        comboBox_20 = new QComboBox(page_5);
        comboBox_20->setObjectName(QString::fromUtf8("comboBox_20"));
        comboBox_20->setGeometry(QRect(60, 80, 171, 22));
        label_44 = new QLabel(page_5);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(40, 120, 91, 16));
        comboBox_21 = new QComboBox(page_5);
        comboBox_21->setObjectName(QString::fromUtf8("comboBox_21"));
        comboBox_21->setGeometry(QRect(60, 150, 171, 22));
        label_45 = new QLabel(page_5);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(40, 190, 59, 16));
        comboBox_22 = new QComboBox(page_5);
        comboBox_22->setObjectName(QString::fromUtf8("comboBox_22"));
        comboBox_22->setGeometry(QRect(60, 210, 171, 32));
        label_46 = new QLabel(page_5);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(30, 250, 59, 16));
        comboBox_23 = new QComboBox(page_5);
        comboBox_23->setObjectName(QString::fromUtf8("comboBox_23"));
        comboBox_23->setGeometry(QRect(60, 280, 171, 32));
        label_47 = new QLabel(page_5);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(30, 330, 59, 16));
        textEdit_8 = new QTextEdit(page_5);
        textEdit_8->setObjectName(QString::fromUtf8("textEdit_8"));
        textEdit_8->setGeometry(QRect(30, 350, 104, 21));
        label_48 = new QLabel(page_5);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(30, 400, 91, 16));
        comboBox_24 = new QComboBox(page_5);
        comboBox_24->setObjectName(QString::fromUtf8("comboBox_24"));
        comboBox_24->setGeometry(QRect(30, 420, 171, 32));
        pushButton_23 = new QPushButton(page_5);
        pushButton_23->setObjectName(QString::fromUtf8("pushButton_23"));
        pushButton_23->setGeometry(QRect(120, 490, 91, 31));
        stackedWidget->addWidget(page_5);
        pushButton_15 = new QPushButton(tab_2);
        pushButton_15->setObjectName(QString::fromUtf8("pushButton_15"));
        pushButton_15->setGeometry(QRect(430, 100, 51, 31));
        pushButton_16 = new QPushButton(tab_2);
        pushButton_16->setObjectName(QString::fromUtf8("pushButton_16"));
        pushButton_16->setGeometry(QRect(430, 160, 51, 31));
        pushButton_17 = new QPushButton(tab_2);
        pushButton_17->setObjectName(QString::fromUtf8("pushButton_17"));
        pushButton_17->setGeometry(QRect(430, 230, 51, 31));
        pushButton_18 = new QPushButton(tab_2);
        pushButton_18->setObjectName(QString::fromUtf8("pushButton_18"));
        pushButton_18->setGeometry(QRect(430, 320, 51, 31));
        tabWidget->addTab(tab_2, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QString::fromUtf8("tab_9"));
        label_18 = new QLabel(tab_9);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(40, 20, 141, 16));
        tableWidget_4 = new QTableWidget(tab_9);
        tableWidget_4->setObjectName(QString::fromUtf8("tableWidget_4"));
        tableWidget_4->setGeometry(QRect(40, 50, 256, 192));
        pushButton_8 = new QPushButton(tab_9);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(40, 260, 81, 32));
        pushButton_9 = new QPushButton(tab_9);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(130, 260, 71, 32));
        pushButton_10 = new QPushButton(tab_9);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(200, 260, 91, 32));
        label_19 = new QLabel(tab_9);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(410, 40, 91, 16));
        textEdit = new QTextEdit(tab_9);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setGeometry(QRect(410, 60, 121, 21));
        label_20 = new QLabel(tab_9);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(410, 110, 81, 16));
        textEdit_2 = new QTextEdit(tab_9);
        textEdit_2->setObjectName(QString::fromUtf8("textEdit_2"));
        textEdit_2->setGeometry(QRect(410, 130, 131, 21));
        label_49 = new QLabel(tab_9);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(410, 170, 81, 16));
        textEdit_9 = new QTextEdit(tab_9);
        textEdit_9->setObjectName(QString::fromUtf8("textEdit_9"));
        textEdit_9->setGeometry(QRect(410, 280, 131, 21));
        label_50 = new QLabel(tab_9);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(650, 30, 111, 16));
        comboBox_25 = new QComboBox(tab_9);
        comboBox_25->setObjectName(QString::fromUtf8("comboBox_25"));
        comboBox_25->setGeometry(QRect(650, 50, 181, 32));
        textEdit_10 = new QTextEdit(tab_9);
        textEdit_10->setObjectName(QString::fromUtf8("textEdit_10"));
        textEdit_10->setGeometry(QRect(410, 200, 151, 21));
        label_51 = new QLabel(tab_9);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(410, 250, 81, 16));
        tabWidget->addTab(tab_9, QString());
        tab_10 = new QWidget();
        tab_10->setObjectName(QString::fromUtf8("tab_10"));
        treeView = new QTreeView(tab_10);
        treeView->setObjectName(QString::fromUtf8("treeView"));
        treeView->setGeometry(QRect(10, 50, 256, 192));
        label_11 = new QLabel(tab_10);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(310, 50, 81, 16));
        comboBox_11 = new QComboBox(tab_10);
        comboBox_11->setObjectName(QString::fromUtf8("comboBox_11"));
        comboBox_11->setGeometry(QRect(300, 80, 171, 32));
        label_12 = new QLabel(tab_10);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 290, 101, 16));
        label_12->setFrameShadow(QFrame::Raised);
        label_12->setTextFormat(Qt::AutoText);
        label_12->setWordWrap(true);
        label_12->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        pushButton_11 = new QPushButton(tab_10);
        pushButton_11->setObjectName(QString::fromUtf8("pushButton_11"));
        pushButton_11->setGeometry(QRect(530, 30, 81, 32));
        pushButton_12 = new QPushButton(tab_10);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(610, 30, 81, 32));
        label_21 = new QLabel(tab_10);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(10, 20, 59, 16));
        textEdit_3 = new QTextEdit(tab_10);
        textEdit_3->setObjectName(QString::fromUtf8("textEdit_3"));
        textEdit_3->setGeometry(QRect(30, 360, 151, 21));
        label_22 = new QLabel(tab_10);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(30, 330, 101, 16));
        label_23 = new QLabel(tab_10);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(30, 400, 91, 16));
        spinBox = new QSpinBox(tab_10);
        spinBox->setObjectName(QString::fromUtf8("spinBox"));
        spinBox->setGeometry(QRect(30, 420, 91, 22));
        pushButton_13 = new QPushButton(tab_10);
        pushButton_13->setObjectName(QString::fromUtf8("pushButton_13"));
        pushButton_13->setGeometry(QRect(20, 470, 113, 32));
        label_24 = new QLabel(tab_10);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(380, 280, 111, 16));
        label_25 = new QLabel(tab_10);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(410, 320, 61, 16));
        comboBox_12 = new QComboBox(tab_10);
        comboBox_12->setObjectName(QString::fromUtf8("comboBox_12"));
        comboBox_12->setGeometry(QRect(410, 340, 221, 32));
        label_26 = new QLabel(tab_10);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(410, 390, 59, 16));
        textEdit_4 = new QTextEdit(tab_10);
        textEdit_4->setObjectName(QString::fromUtf8("textEdit_4"));
        textEdit_4->setGeometry(QRect(420, 410, 81, 21));
        pushButton_14 = new QPushButton(tab_10);
        pushButton_14->setObjectName(QString::fromUtf8("pushButton_14"));
        pushButton_14->setGeometry(QRect(410, 460, 113, 32));
        tabWidget->addTab(tab_10, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        tableWidget_41 = new QTableWidget(tab_3);
        tableWidget_41->setObjectName(QString::fromUtf8("tableWidget_41"));
        tableWidget_41->setGeometry(QRect(10, 10, 231, 391));
        label_131 = new QLabel(tab_3);
        label_131->setObjectName(QString::fromUtf8("label_131"));
        label_131->setGeometry(QRect(250, 10, 81, 16));
        label_141 = new QLabel(tab_3);
        label_141->setObjectName(QString::fromUtf8("label_141"));
        label_141->setGeometry(QRect(470, 20, 51, 16));
        radioButton = new QRadioButton(tab_3);
        radioButton->setObjectName(QString::fromUtf8("radioButton"));
        radioButton->setGeometry(QRect(520, 20, 63, 16));
        radioButton_2 = new QRadioButton(tab_3);
        radioButton_2->setObjectName(QString::fromUtf8("radioButton_2"));
        radioButton_2->setGeometry(QRect(560, 20, 63, 16));
        label_161 = new QLabel(tab_3);
        label_161->setObjectName(QString::fromUtf8("label_161"));
        label_161->setGeometry(QRect(470, 40, 141, 16));
        comboBox_81 = new QComboBox(tab_3);
        comboBox_81->setObjectName(QString::fromUtf8("comboBox_81"));
        comboBox_81->setGeometry(QRect(470, 60, 161, 22));
        label_171 = new QLabel(tab_3);
        label_171->setObjectName(QString::fromUtf8("label_171"));
        label_171->setGeometry(QRect(470, 90, 241, 16));
        label_181 = new QLabel(tab_3);
        label_181->setObjectName(QString::fromUtf8("label_181"));
        label_181->setGeometry(QRect(470, 120, 101, 16));
        label_191 = new QLabel(tab_3);
        label_191->setObjectName(QString::fromUtf8("label_191"));
        label_191->setGeometry(QRect(470, 140, 35, 10));
        comboBox_101 = new QComboBox(tab_3);
        comboBox_101->setObjectName(QString::fromUtf8("comboBox_101"));
        comboBox_101->setGeometry(QRect(500, 140, 81, 22));
        label_201 = new QLabel(tab_3);
        label_201->setObjectName(QString::fromUtf8("label_201"));
        label_201->setGeometry(QRect(600, 140, 41, 16));
        comboBox_111 = new QComboBox(tab_3);
        comboBox_111->setObjectName(QString::fromUtf8("comboBox_111"));
        comboBox_111->setGeometry(QRect(650, 140, 55, 22));
        lineEdit_2 = new QLineEdit(tab_3);
        lineEdit_2->setObjectName(QString::fromUtf8("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(250, 90, 113, 21));
        label_211 = new QLabel(tab_3);
        label_211->setObjectName(QString::fromUtf8("label_211"));
        label_211->setGeometry(QRect(250, 70, 81, 16));
        label_221 = new QLabel(tab_3);
        label_221->setObjectName(QString::fromUtf8("label_221"));
        label_221->setGeometry(QRect(250, 120, 81, 16));
        lineEdit_3 = new QLineEdit(tab_3);
        lineEdit_3->setObjectName(QString::fromUtf8("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(250, 140, 113, 21));
        label_231 = new QLabel(tab_3);
        label_231->setObjectName(QString::fromUtf8("label_231"));
        label_231->setGeometry(QRect(250, 170, 81, 16));
        lineEdit_4 = new QLineEdit(tab_3);
        lineEdit_4->setObjectName(QString::fromUtf8("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(250, 190, 113, 21));
        lineEdit_4->setMaxLength(1);
        lineEdit_5 = new QLineEdit(tab_3);
        lineEdit_5->setObjectName(QString::fromUtf8("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(250, 30, 113, 21));
        pushButton_81 = new QPushButton(tab_3);
        pushButton_81->setObjectName(QString::fromUtf8("pushButton_81"));
        pushButton_81->setGeometry(QRect(370, 30, 61, 16));
        label_241 = new QLabel(tab_3);
        label_241->setObjectName(QString::fromUtf8("label_241"));
        label_241->setGeometry(QRect(250, 220, 81, 16));
        lineEdit_6 = new QLineEdit(tab_3);
        lineEdit_6->setObjectName(QString::fromUtf8("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(250, 240, 113, 21));
        lineEdit_6->setMaxLength(1);
        pushButton_91 = new QPushButton(tab_3);
        pushButton_91->setObjectName(QString::fromUtf8("pushButton_91"));
        pushButton_91->setGeometry(QRect(470, 240, 141, 16));
        pushButton_101 = new QPushButton(tab_3);
        pushButton_101->setObjectName(QString::fromUtf8("pushButton_101"));
        pushButton_101->setGeometry(QRect(370, 50, 61, 16));
        tabWidget->addTab(tab_3, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        pushButton = new QPushButton(tab_5);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(500, 10, 131, 31));
        pushButton_2 = new QPushButton(tab_5);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(500, 90, 141, 31));
        pushButton_3 = new QPushButton(tab_5);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(500, 50, 121, 31));
        tableView = new QTableView(tab_5);
        tableView->setObjectName(QString::fromUtf8("tableView"));
        tableView->setGeometry(QRect(10, 10, 471, 401));
        tabWidget->addTab(tab_5, QString());
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1028, 20));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(4);
        stackedWidget->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        label->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Major:", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Course:", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "Add Class", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "Remove Class", nullptr));
        pushButton_4->setText(QApplication::translate("MainWindow", "Remove", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "Current Schedule:", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "First Name:", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "Last Name:", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "Middle Initial:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Student", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "College:", nullptr));
        pushButton_5->setText(QApplication::translate("MainWindow", "Add", nullptr));
        pushButton_6->setText(QApplication::translate("MainWindow", "Edit", nullptr));
        pushButton_7->setText(QApplication::translate("MainWindow", "Remove", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "Major", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "Course", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "Sections", nullptr));
        label_27->setText(QApplication::translate("MainWindow", "Add or Edit College", nullptr));
        label_28->setText(QApplication::translate("MainWindow", "College Name:", nullptr));
        pushButton_19->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_29->setText(QApplication::translate("MainWindow", "Add or Edit Department", nullptr));
        label_30->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_31->setText(QApplication::translate("MainWindow", "Department Name:", nullptr));
        pushButton_20->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_36->setText(QApplication::translate("MainWindow", "Department Head:", nullptr));
        label_32->setText(QApplication::translate("MainWindow", "Add or Edit Major", nullptr));
        label_33->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_34->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_35->setText(QApplication::translate("MainWindow", "Major Name:", nullptr));
        pushButton_21->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_37->setText(QApplication::translate("MainWindow", "Add or Edit Course", nullptr));
        label_38->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_39->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_40->setText(QApplication::translate("MainWindow", "Major", nullptr));
        label_41->setText(QApplication::translate("MainWindow", "Course Name:", nullptr));
        pushButton_22->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_42->setText(QApplication::translate("MainWindow", "Add or Edit Section", nullptr));
        label_43->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_44->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_45->setText(QApplication::translate("MainWindow", "Major:", nullptr));
        label_46->setText(QApplication::translate("MainWindow", "Course:", nullptr));
        label_47->setText(QApplication::translate("MainWindow", "Section #:", nullptr));
        label_48->setText(QApplication::translate("MainWindow", "Professor:", nullptr));
        pushButton_23->setText(QApplication::translate("MainWindow", "Save", nullptr));
        pushButton_15->setText(QApplication::translate("MainWindow", "Add", nullptr));
        pushButton_16->setText(QApplication::translate("MainWindow", "Add", nullptr));
        pushButton_17->setText(QApplication::translate("MainWindow", "Add", nullptr));
        pushButton_18->setText(QApplication::translate("MainWindow", "Add", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "University", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "Employee List:", nullptr));
        pushButton_8->setText(QApplication::translate("MainWindow", "Add", nullptr));
        pushButton_9->setText(QApplication::translate("MainWindow", "Edit", nullptr));
        pushButton_10->setText(QApplication::translate("MainWindow", "Delete", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "First Name", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "Last Name", nullptr));
        label_49->setText(QApplication::translate("MainWindow", "MI:", nullptr));
        label_50->setText(QApplication::translate("MainWindow", "Employee Title:", nullptr));
        label_51->setText(QApplication::translate("MainWindow", "Salary:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_9), QApplication::translate("MainWindow", "Employees", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "Buildings:", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "Add Building", nullptr));
        pushButton_11->setText(QApplication::translate("MainWindow", "Delete", nullptr));
        pushButton_12->setText(QApplication::translate("MainWindow", "Edit", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "Rooms:", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "Building Name:", nullptr));
        label_23->setText(QApplication::translate("MainWindow", "Rooms inside", nullptr));
        pushButton_13->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_24->setText(QApplication::translate("MainWindow", "Add Room", nullptr));
        label_25->setText(QApplication::translate("MainWindow", "Building:", nullptr));
        label_26->setText(QApplication::translate("MainWindow", "Room #:", nullptr));
        pushButton_14->setText(QApplication::translate("MainWindow", "Save", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_10), QApplication::translate("MainWindow", "Rooms", nullptr));
        label_131->setText(QApplication::translate("MainWindow", "Find Student by ID: ", nullptr));
        label_141->setText(QApplication::translate("MainWindow", "Registered?", nullptr));
        radioButton->setText(QApplication::translate("MainWindow", "Yes", nullptr));
        radioButton_2->setText(QApplication::translate("MainWindow", "No", nullptr));
        label_161->setText(QApplication::translate("MainWindow", "Tuition paid for (Choose all that apply): ", nullptr));
        label_171->setText(QApplication::translate("MainWindow", "<List of the semesters this Admin chooses, updated with choice>", nullptr));
        label_181->setText(QApplication::translate("MainWindow", "Update student grade: ", nullptr));
        label_191->setText(QApplication::translate("MainWindow", "Course: ", nullptr));
        label_201->setText(QApplication::translate("MainWindow", "New Grade:", nullptr));
        label_211->setText(QApplication::translate("MainWindow", "Student First Name:", nullptr));
        label_221->setText(QApplication::translate("MainWindow", "Student Last Name:", nullptr));
        label_231->setText(QApplication::translate("MainWindow", "Student Middle Initial:", nullptr));
        pushButton_81->setText(QApplication::translate("MainWindow", "Enter", nullptr));
        label_241->setText(QApplication::translate("MainWindow", "Student ID:", nullptr));
        pushButton_91->setText(QApplication::translate("MainWindow", "Save", nullptr));
        pushButton_101->setText(QApplication::translate("MainWindow", "Add Student", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "Admin", nullptr));
        pushButton->setText(QApplication::translate("MainWindow", "Create Admin", nullptr));
        pushButton_2->setText(QApplication::translate("MainWindow", "Delete Admin", nullptr));
        pushButton_3->setText(QApplication::translate("MainWindow", "Edit Admin", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("MainWindow", "Super Admin", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
