/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QTimeEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QComboBox *studentCollegeComboBox;
    QComboBox *studentDepartmentComboBox;
    QComboBox *studentMajorComboBox;
    QComboBox *studentCourseComboBox;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLineEdit *lineEdit;
    QLabel *label_5;
    QLabel *label_6;
    QComboBox *comboBox_5;
    QPushButton *pushButton_4;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_61;
    QTableView *studentCourseTable;
    QTableView *tableView;
    QTableView *studentCourseTable1;
    QTableView *tableView1;
    QWidget *tab_2;
    QComboBox *departmentBox;
    QLabel *label_15;
    QComboBox *collegeBox;
    QPushButton *addCollege;
    QPushButton *editUnoversity;
    QPushButton *removeUniversity;
    QLabel *label_13;
    QLabel *label_14;
    QComboBox *majorBox;
    QLabel *label_16;
    QComboBox *courseBox;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QLabel *label_27;
    QLabel *label_28;
    QPushButton *pushButton_19;
    QLineEdit *lineEdit_11;
    QWidget *page_2;
    QLabel *label_29;
    QLabel *label_30;
    QComboBox *comboBox_13;
    QLabel *label_31;
    QPushButton *pushButton_20;
    QLabel *label_36;
    QComboBox *comboBox_16;
    QLineEdit *lineEdit_2;
    QWidget *page_3;
    QLabel *label_32;
    QLabel *label_33;
    QComboBox *comboBox_14;
    QLabel *label_34;
    QComboBox *comboBox_15;
    QLabel *label_35;
    QPushButton *pushButton_21;
    QLineEdit *lineEdit_3;
    QWidget *page_4;
    QLabel *label_37;
    QLabel *label_38;
    QComboBox *comboBox_17;
    QLabel *label_39;
    QComboBox *comboBox_18;
    QLabel *label_40;
    QComboBox *comboBox_19;
    QLabel *label_41;
    QPushButton *pushButton_22;
    QLineEdit *lineEdit_4;
    QWidget *page_5;
    QLabel *label_42;
    QLabel *label_43;
    QComboBox *comboBox_20;
    QLabel *label_44;
    QComboBox *comboBox_21;
    QLabel *label_45;
    QComboBox *comboBox_22;
    QLabel *label_46;
    QComboBox *comboBox_23;
    QLabel *label_47;
    QLabel *label_48;
    QComboBox *comboBox_24;
    QPushButton *pushButton_23;
    QLabel *label_54;
    QTimeEdit *timeEdit;
    QLabel *label_55;
    QTimeEdit *timeEdit_2;
    QLabel *label_56;
    QLabel *label_57;
    QComboBox *comboBox_28;
    QLabel *label_62;
    QComboBox *comboBox_31;
    QLabel *label_63;
    QComboBox *comboBox_32;
    QLineEdit *lineEdit_9;
    QLineEdit *lineEdit_10;
    QWidget *page_6;
    QPushButton *pushButton_15;
    QPushButton *addMajor;
    QPushButton *addCourse;
    QLabel *label_52;
    QComboBox *yearBox;
    QLabel *label_53;
    QComboBox *semesterBox;
    QTableView *universityTable;
    QPushButton *addSection;
    QWidget *tab_9;
    QLabel *label_18;
    QPushButton *addEmployee;
    QPushButton *editEmployee;
    QPushButton *deleteEmployee;
    QTableView *employeeTable;
    QStackedWidget *stackedWidget_2;
    QWidget *page_22;
    QWidget *page_14;
    QLabel *label_19;
    QLineEdit *EmployeeFirstName;
    QLabel *label_20;
    QLineEdit *employeeLastName;
    QLabel *label_49;
    QLineEdit *employeeMI;
    QLabel *label_51;
    QLineEdit *employeeSalary;
    QPushButton *employeeSave;
    QWidget *page_15;
    QLabel *label_25;
    QLineEdit *EmployeeFirstName_2;
    QLabel *label_50;
    QLineEdit *employeeLastName_2;
    QLabel *label_73;
    QLineEdit *employeeMI_2;
    QLabel *label_74;
    QLineEdit *employeeSalary_2;
    QPushButton *employeeSave_2;
    QWidget *roomsTab;
    QTableView *roomsTable;
    QLabel *label_11;
    QComboBox *buildingsComboBox;
    QPushButton *deleteRoom;
    QPushButton *editRoom;
    QLabel *label_21;
    QPushButton *deleteBuilding;
    QPushButton *editBuilding;
    QPushButton *pushButton;
    QStackedWidget *editRoomStackedWidget;
    QWidget *page_12;
    QWidget *page_13;
    QLabel *label_24;
    QLabel *label_26;
    QLineEdit *roomNumberLineEdit;
    QLabel *label_69;
    QSpinBox *spinBox_2;
    QPushButton *saveRoom;
    QStackedWidget *addRoomStackedWidget;
    QWidget *page_16;
    QWidget *page_17;
    QLabel *label_75;
    QLabel *label_76;
    QLineEdit *roomNumberLineEdit_3;
    QLabel *label_77;
    QSpinBox *spinBox_4;
    QPushButton *saveRoom_3;
    QStackedWidget *addBuildingStackedWidget;
    QWidget *page_18;
    QLabel *label_78;
    QLabel *addBuildingNameLabel;
    QLineEdit *addBuildingNameLineEdit;
    QPushButton *saveBuilding_2;
    QWidget *page_19;
    QStackedWidget *editBuildingStackedWidget;
    QWidget *page_20;
    QLabel *label_12;
    QLabel *label_22;
    QLineEdit *editBuildingNameLineEdit;
    QPushButton *saveBuilding;
    QWidget *page_21;
    QPushButton *addBuilding;
    QSpinBox *spinBox_21;
    QTableView *roomsTable;
    QTableView *roomsTable1;
    QWidget *adminTab;
    QLineEdit *studentIDLineEdit;
    QLabel *label_64;
    QPushButton *findStudentEnter;
    QPushButton *deleteStudent;
    QTableView *studentsTable;
    QPushButton *addStudent;
    QStackedWidget *studentInfoStackedWidget;
    QWidget *page_11;
    QWidget *stackedWidget_2Page1;
    QLabel *label_65;
    QLineEdit *studentFirstNameLineEdit;
    QLabel *label_220;
    QLineEdit *studentLastNameLineEdit;
    QLabel *label_230;
    QLineEdit *studentMILineEdit;
    QLabel *label_66;
    QPushButton *saveStudentData;
    QWidget *widget;
    QLabel *label_160;
    QLabel *label_161;
    QRadioButton *radioButton;
    QRadioButton *radioButton_2;
    QWidget *widget_3;
    QLabel *label_67;
    QLabel *label_68;
    QComboBox *studentGradeCourseComboBox;
    QLabel *label_200;
    QComboBox *studentGradeNewGradeComboBox;
    QPushButton *saveStudentGrade;
    QPushButton *semesterEnter;
    QLineEdit *semesterLineEdit;
    QLineEdit *yearLineEdit;
    QLabel *label_58;
    QLabel *label_72;
    QLabel *label_23;
    QTableView *studentsTable;
    QWidget *superAdminTab;
    QPushButton *deleteAdmin;
    QPushButton *editAdmin;
    QPushButton *addAdmin;
    QLabel *label_71;
    QStackedWidget *editAdminStackedWidget;
    QWidget *page_7;
    QWidget *page_8;
    QLabel *adminNewNameLabel;
    QLineEdit *editAdminPasswordLineEdit;
    QPushButton *editAdminEnterPushButton;
    QLabel *label_25;
    QLineEdit *editAdminIDLineEdit;
    QStackedWidget *addAdminStackedWidget;
    QWidget *page_9;
    QWidget *page_10;
    QLabel *adminNameLabel;
    QLineEdit *newAdminLineEdit;
    QPushButton *addAdminEnterPushButton;
    QTableView *adminTable;
    QStackedWidget *deleteAdminStackedWidget;
    QWidget *page_14;
    QWidget *page_15;
    QLabel *deleteAdminIDLabel;
    QLineEdit *deleteAdminLineEdit;
    QPushButton *deleteAdminEnterPushButton;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1028, 715);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setEnabled(true);
        tabWidget->setGeometry(QRect(0, 0, 1031, 651));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        studentCollegeComboBox = new QComboBox(tab);
        studentCollegeComboBox->setObjectName(QStringLiteral("studentCollegeComboBox"));
        studentCollegeComboBox->setGeometry(QRect(0, 50, 161, 22));
        studentDepartmentComboBox = new QComboBox(tab);
        studentDepartmentComboBox->setObjectName(QStringLiteral("studentDepartmentComboBox"));
        studentDepartmentComboBox->setGeometry(QRect(0, 130, 191, 22));
        studentMajorComboBox = new QComboBox(tab);
        studentMajorComboBox->setObjectName(QStringLiteral("studentMajorComboBox"));
        studentMajorComboBox->setGeometry(QRect(10, 200, 181, 22));
        studentCourseComboBox = new QComboBox(tab);
        studentCourseComboBox->setObjectName(QStringLiteral("studentCourseComboBox"));
        studentCourseComboBox->setGeometry(QRect(20, 270, 171, 22));
        label = new QLabel(tab);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 20, 71, 16));
        label_2 = new QLabel(tab);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 90, 81, 16));
        label_3 = new QLabel(tab);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(20, 170, 71, 16));
        label_4 = new QLabel(tab);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(20, 240, 111, 16));
        lineEdit = new QLineEdit(tab);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(30, 360, 113, 21));
        label_5 = new QLabel(tab);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(30, 330, 71, 16));
        label_6 = new QLabel(tab);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(460, 270, 91, 16));
        comboBox_5 = new QComboBox(tab);
        comboBox_5->setObjectName(QStringLiteral("comboBox_5"));
        comboBox_5->setGeometry(QRect(460, 290, 241, 22));
        pushButton_4 = new QPushButton(tab);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(710, 280, 80, 31));
        label_7 = new QLabel(tab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(460, 220, 111, 16));
        label_8 = new QLabel(tab);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(470, 20, 71, 16));
        label_9 = new QLabel(tab);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(470, 60, 71, 16));
        label_10 = new QLabel(tab);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(770, 20, 91, 16));
        label_61 = new QLabel(tab);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(770, 60, 71, 16));
        studentCourseTable = new QTableView(tab);
        studentCourseTable->setObjectName(QStringLiteral("studentCourseTable"));
        studentCourseTable->setGeometry(QRect(10, 11, 231, 501));
        tableView = new QTableView(tab);
        tableView->setObjectName(QStringLiteral("tableView"));
        tableView->setGeometry(QRect(460, 240, 381, 241));
        studentCourseTable1 = new QTableView(tab);
        studentCourseTable1->setObjectName(QStringLiteral("studentCourseTable1"));
        studentCourseTable1->setGeometry(QRect(10, 401, 781, 191));
        tableView1 = new QTableView(tab);
        tableView1->setObjectName(QStringLiteral("tableView1"));
        tableView1->setGeometry(QRect(460, 110, 561, 151));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        departmentBox = new QComboBox(tab_2);
        departmentBox->setObjectName(QStringLiteral("departmentBox"));
        departmentBox->setGeometry(QRect(230, 20, 211, 22));
        label_15 = new QLabel(tab_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 0, 71, 16));
        collegeBox = new QComboBox(tab_2);
        collegeBox->setObjectName(QStringLiteral("collegeBox"));
        collegeBox->setGeometry(QRect(10, 20, 211, 22));
        addCollege = new QPushButton(tab_2);
        addCollege->setObjectName(QStringLiteral("addCollege"));
        addCollege->setGeometry(QRect(110, 590, 71, 21));
        editUnoversity = new QPushButton(tab_2);
        editUnoversity->setObjectName(QStringLiteral("editUnoversity"));
        editUnoversity->setGeometry(QRect(10, 590, 31, 21));
        removeUniversity = new QPushButton(tab_2);
        removeUniversity->setObjectName(QStringLiteral("removeUniversity"));
        removeUniversity->setGeometry(QRect(50, 590, 51, 21));
        label_13 = new QLabel(tab_2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(230, 0, 91, 16));
        label_14 = new QLabel(tab_2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 50, 59, 16));
        majorBox = new QComboBox(tab_2);
        majorBox->setObjectName(QStringLiteral("majorBox"));
        majorBox->setGeometry(QRect(10, 70, 211, 21));
        label_16 = new QLabel(tab_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(230, 50, 59, 16));
        courseBox = new QComboBox(tab_2);
        courseBox->setObjectName(QStringLiteral("courseBox"));
        courseBox->setGeometry(QRect(230, 70, 211, 21));
        stackedWidget = new QStackedWidget(tab_2);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setEnabled(true);
        stackedWidget->setGeometry(QRect(540, 30, 481, 551));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        label_27 = new QLabel(page);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(100, 10, 131, 16));
        label_28 = new QLabel(page);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(40, 50, 91, 16));
        pushButton_19 = new QPushButton(page);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(70, 220, 91, 31));
        lineEdit_11 = new QLineEdit(page);
        lineEdit_11->setObjectName(QStringLiteral("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(40, 70, 171, 21));
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        page_2->setEnabled(true);
        label_29 = new QLabel(page_2);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(100, 20, 141, 16));
        label_30 = new QLabel(page_2);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(50, 70, 71, 16));
        comboBox_13 = new QComboBox(page_2);
        comboBox_13->setObjectName(QStringLiteral("comboBox_13"));
        comboBox_13->setGeometry(QRect(60, 100, 171, 22));
        label_31 = new QLabel(page_2);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(50, 150, 131, 16));
        pushButton_20 = new QPushButton(page_2);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(110, 350, 91, 31));
        label_36 = new QLabel(page_2);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(50, 220, 131, 16));
        comboBox_16 = new QComboBox(page_2);
        comboBox_16->setObjectName(QStringLiteral("comboBox_16"));
        comboBox_16->setGeometry(QRect(60, 250, 171, 22));
        lineEdit_2 = new QLineEdit(page_2);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(70, 180, 171, 21));
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        label_32 = new QLabel(page_3);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(110, 30, 141, 16));
        label_33 = new QLabel(page_3);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(70, 80, 71, 16));
        comboBox_14 = new QComboBox(page_3);
        comboBox_14->setObjectName(QStringLiteral("comboBox_14"));
        comboBox_14->setGeometry(QRect(80, 110, 171, 22));
        label_34 = new QLabel(page_3);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(70, 150, 91, 16));
        comboBox_15 = new QComboBox(page_3);
        comboBox_15->setObjectName(QStringLiteral("comboBox_15"));
        comboBox_15->setGeometry(QRect(80, 190, 171, 22));
        label_35 = new QLabel(page_3);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(80, 240, 111, 16));
        pushButton_21 = new QPushButton(page_3);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(130, 310, 91, 31));
        lineEdit_3 = new QLineEdit(page_3);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(110, 270, 171, 21));
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        label_37 = new QLabel(page_4);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(120, 30, 141, 16));
        label_38 = new QLabel(page_4);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(40, 80, 71, 16));
        comboBox_17 = new QComboBox(page_4);
        comboBox_17->setObjectName(QStringLiteral("comboBox_17"));
        comboBox_17->setGeometry(QRect(50, 100, 171, 22));
        label_39 = new QLabel(page_4);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(40, 150, 91, 16));
        comboBox_18 = new QComboBox(page_4);
        comboBox_18->setObjectName(QStringLiteral("comboBox_18"));
        comboBox_18->setGeometry(QRect(50, 170, 171, 22));
        label_40 = new QLabel(page_4);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(50, 210, 59, 16));
        comboBox_19 = new QComboBox(page_4);
        comboBox_19->setObjectName(QStringLiteral("comboBox_19"));
        comboBox_19->setGeometry(QRect(50, 230, 171, 32));
        label_41 = new QLabel(page_4);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(50, 280, 91, 16));
        pushButton_22 = new QPushButton(page_4);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(120, 360, 91, 31));
        lineEdit_4 = new QLineEdit(page_4);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(60, 310, 171, 21));
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        label_42 = new QLabel(page_5);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(110, 20, 141, 16));
        label_43 = new QLabel(page_5);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(40, 60, 71, 16));
        comboBox_20 = new QComboBox(page_5);
        comboBox_20->setObjectName(QStringLiteral("comboBox_20"));
        comboBox_20->setGeometry(QRect(30, 80, 171, 22));
        label_44 = new QLabel(page_5);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(40, 120, 91, 16));
        comboBox_21 = new QComboBox(page_5);
        comboBox_21->setObjectName(QStringLiteral("comboBox_21"));
        comboBox_21->setGeometry(QRect(30, 150, 171, 22));
        label_45 = new QLabel(page_5);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(40, 190, 59, 16));
        comboBox_22 = new QComboBox(page_5);
        comboBox_22->setObjectName(QStringLiteral("comboBox_22"));
        comboBox_22->setGeometry(QRect(30, 210, 171, 32));
        label_46 = new QLabel(page_5);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(30, 250, 59, 16));
        comboBox_23 = new QComboBox(page_5);
        comboBox_23->setObjectName(QStringLiteral("comboBox_23"));
        comboBox_23->setGeometry(QRect(30, 270, 171, 32));
        label_47 = new QLabel(page_5);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(30, 330, 59, 16));
        label_48 = new QLabel(page_5);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(30, 400, 91, 16));
        comboBox_24 = new QComboBox(page_5);
        comboBox_24->setObjectName(QStringLiteral("comboBox_24"));
        comboBox_24->setGeometry(QRect(20, 420, 171, 32));
        pushButton_23 = new QPushButton(page_5);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(40, 520, 91, 31));
        label_54 = new QLabel(page_5);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(280, 60, 71, 16));
        timeEdit = new QTimeEdit(page_5);
        timeEdit->setObjectName(QStringLiteral("timeEdit"));
        timeEdit->setGeometry(QRect(280, 80, 118, 22));
        label_55 = new QLabel(page_5);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(280, 120, 71, 16));
        timeEdit_2 = new QTimeEdit(page_5);
        timeEdit_2->setObjectName(QStringLiteral("timeEdit_2"));
        timeEdit_2->setGeometry(QRect(280, 140, 118, 22));
        label_56 = new QLabel(page_5);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(280, 190, 59, 16));
        label_57 = new QLabel(page_5);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(280, 280, 81, 16));
        comboBox_28 = new QComboBox(page_5);
        comboBox_28->setObjectName(QStringLiteral("comboBox_28"));
        comboBox_28->setGeometry(QRect(280, 300, 91, 32));
        label_62 = new QLabel(page_5);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(280, 380, 61, 16));
        comboBox_31 = new QComboBox(page_5);
        comboBox_31->setObjectName(QStringLiteral("comboBox_31"));
        comboBox_31->setGeometry(QRect(250, 400, 221, 32));
        label_63 = new QLabel(page_5);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(260, 460, 59, 16));
        comboBox_32 = new QComboBox(page_5);
        comboBox_32->setObjectName(QStringLiteral("comboBox_32"));
        comboBox_32->setGeometry(QRect(250, 480, 221, 32));
        lineEdit_9 = new QLineEdit(page_5);
        lineEdit_9->setObjectName(QStringLiteral("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(280, 220, 171, 21));
        lineEdit_10 = new QLineEdit(page_5);
        lineEdit_10->setObjectName(QStringLiteral("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(30, 360, 101, 21));
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        stackedWidget->addWidget(page_6);
        pushButton_15 = new QPushButton(tab_2);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(190, 590, 91, 21));
        addMajor = new QPushButton(tab_2);
        addMajor->setObjectName(QStringLiteral("addMajor"));
        addMajor->setGeometry(QRect(290, 590, 61, 21));
        addCourse = new QPushButton(tab_2);
        addCourse->setObjectName(QStringLiteral("addCourse"));
        addCourse->setGeometry(QRect(360, 590, 71, 21));
        label_52 = new QLabel(tab_2);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(450, 0, 59, 16));
        yearBox = new QComboBox(tab_2);
        yearBox->setObjectName(QStringLiteral("yearBox"));
        yearBox->setGeometry(QRect(450, 20, 101, 21));
        label_53 = new QLabel(tab_2);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(450, 50, 81, 16));
        semesterBox = new QComboBox(tab_2);
        semesterBox->setObjectName(QStringLiteral("semesterBox"));
        semesterBox->setGeometry(QRect(450, 70, 101, 21));
        universityTable = new QTableView(tab_2);
        universityTable->setObjectName(QStringLiteral("universityTable"));
        universityTable->setGeometry(QRect(10, 111, 541, 471));
        addSection = new QPushButton(tab_2);
        addSection->setObjectName(QStringLiteral("addSection"));
        addSection->setGeometry(QRect(440, 590, 71, 21));
        tabWidget->addTab(tab_2, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QStringLiteral("tab_9"));
        label_18 = new QLabel(tab_9);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(40, 20, 141, 16));
        addEmployee = new QPushButton(tab_9);
        addEmployee->setObjectName(QStringLiteral("addEmployee"));
        addEmployee->setGeometry(QRect(40, 260, 81, 32));
        editEmployee = new QPushButton(tab_9);
        editEmployee->setObjectName(QStringLiteral("editEmployee"));
        editEmployee->setGeometry(QRect(130, 260, 71, 32));
        deleteEmployee = new QPushButton(tab_9);
        deleteEmployee->setObjectName(QStringLiteral("deleteEmployee"));
        deleteEmployee->setGeometry(QRect(630, 260, 91, 32));
        employeeTable = new QTableView(tab_9);
        employeeTable->setObjectName(QStringLiteral("employeeTable"));
        employeeTable->setGeometry(QRect(10, 40, 711, 211));
        stackedWidget_2 = new QStackedWidget(tab_9);
        stackedWidget_2->setObjectName(QStringLiteral("stackedWidget_2"));
        stackedWidget_2->setGeometry(QRect(70, 299, 741, 261));
        page_22 = new QWidget();
        page_22->setObjectName(QStringLiteral("page_22"));
        stackedWidget_2->addWidget(page_22);
        page_14 = new QWidget();
        page_14->setObjectName(QStringLiteral("page_14"));
        label_19 = new QLabel(page_14);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(20, 30, 91, 16));
        EmployeeFirstName = new QLineEdit(page_14);
        EmployeeFirstName->setObjectName(QStringLiteral("EmployeeFirstName"));
        EmployeeFirstName->setGeometry(QRect(20, 60, 171, 21));
        label_20 = new QLabel(page_14);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(300, 20, 81, 16));
        employeeLastName = new QLineEdit(page_14);
        employeeLastName->setObjectName(QStringLiteral("employeeLastName"));
        employeeLastName->setGeometry(QRect(290, 60, 171, 21));
        label_49 = new QLabel(page_14);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(500, 30, 81, 16));
        employeeMI = new QLineEdit(page_14);
        employeeMI->setObjectName(QStringLiteral("employeeMI"));
        employeeMI->setGeometry(QRect(500, 60, 51, 21));
        label_51 = new QLabel(page_14);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(30, 140, 81, 16));
        employeeSalary = new QLineEdit(page_14);
        employeeSalary->setObjectName(QStringLiteral("employeeSalary"));
        employeeSalary->setGeometry(QRect(20, 170, 171, 21));
        employeeSave = new QPushButton(page_14);
        employeeSave->setObjectName(QStringLiteral("employeeSave"));
        employeeSave->setGeometry(QRect(290, 230, 91, 32));
        stackedWidget_2->addWidget(page_14);
        page_15 = new QWidget();
        page_15->setObjectName(QStringLiteral("page_15"));
        label_25 = new QLabel(page_15);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(50, 40, 91, 16));
        EmployeeFirstName_2 = new QLineEdit(page_15);
        EmployeeFirstName_2->setObjectName(QStringLiteral("EmployeeFirstName_2"));
        EmployeeFirstName_2->setGeometry(QRect(40, 60, 171, 21));
        label_50 = new QLabel(page_15);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(360, 30, 81, 16));
        employeeLastName_2 = new QLineEdit(page_15);
        employeeLastName_2->setObjectName(QStringLiteral("employeeLastName_2"));
        employeeLastName_2->setGeometry(QRect(350, 60, 171, 21));
        label_73 = new QLabel(page_15);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(600, 30, 81, 16));
        employeeMI_2 = new QLineEdit(page_15);
        employeeMI_2->setObjectName(QStringLiteral("employeeMI_2"));
        employeeMI_2->setGeometry(QRect(610, 60, 51, 21));
        label_74 = new QLabel(page_15);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(60, 140, 81, 16));
        employeeSalary_2 = new QLineEdit(page_15);
        employeeSalary_2->setObjectName(QStringLiteral("employeeSalary_2"));
        employeeSalary_2->setGeometry(QRect(50, 170, 171, 21));
        employeeSave_2 = new QPushButton(page_15);
        employeeSave_2->setObjectName(QStringLiteral("employeeSave_2"));
        employeeSave_2->setGeometry(QRect(380, 200, 91, 32));
        stackedWidget_2->addWidget(page_15);
        tabWidget->addTab(tab_9, QString());
        roomsTab = new QWidget();
        roomsTab->setObjectName(QString::fromUtf8("roomsTab"));
        roomsTable = new QTableView(roomsTab);
        roomsTable->setObjectName(QString::fromUtf8("roomsTable"));
        roomsTable->setGeometry(QRect(10, 40, 281, 201));
        roomsTable->setShowGrid(true);
        label_11 = new QLabel(roomsTab);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(319, 15, 261, 21));
        buildingsComboBox = new QComboBox(roomsTab);
        buildingsComboBox->setObjectName(QStringLiteral("buildingsComboBox"));
        buildingsComboBox->setGeometry(QRect(320, 40, 251, 32));
        buildingsComboBox->setEditable(true);
        deleteRoom = new QPushButton(roomsTab);
        deleteRoom->setObjectName(QStringLiteral("deleteRoom"));
        deleteRoom->setGeometry(QRect(10, 250, 111, 32));
        editRoom = new QPushButton(roomsTab);
        editRoom->setObjectName(QStringLiteral("editRoom"));
        editRoom->setGeometry(QRect(130, 250, 111, 32));
        label_21 = new QLabel(roomsTab);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 20, 59, 16));
        deleteBuilding = new QPushButton(roomsTab);
        deleteBuilding->setObjectName(QStringLiteral("deleteBuilding"));
        deleteBuilding->setGeometry(QRect(320, 80, 121, 32));
        editBuilding = new QPushButton(roomsTab);
        editBuilding->setObjectName(QStringLiteral("editBuilding"));
        editBuilding->setGeometry(QRect(450, 80, 121, 32));
        pushButton = new QPushButton(roomsTab);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(250, 250, 111, 31));
        editRoomStackedWidget = new QStackedWidget(roomsTab);
        editRoomStackedWidget->setObjectName(QStringLiteral("editRoomStackedWidget"));
        editRoomStackedWidget->setGeometry(QRect(10, 290, 171, 161));
        page_12 = new QWidget();
        page_12->setObjectName(QStringLiteral("page_12"));
        editRoomStackedWidget->addWidget(page_12);
        page_13 = new QWidget();
        page_13->setObjectName(QStringLiteral("page_13"));
        label_24 = new QLabel(page_13);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(0, 0, 120, 16));
        label_26 = new QLabel(page_13);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(20, 20, 59, 16));
        roomNumberLineEdit = new QLineEdit(page_13);
        roomNumberLineEdit->setObjectName(QStringLiteral("roomNumberLineEdit"));
        roomNumberLineEdit->setGeometry(QRect(20, 40, 81, 21));
        label_69 = new QLabel(page_13);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(20, 70, 201, 16));
        spinBox_2 = new QSpinBox(page_13);
        spinBox_2->setObjectName(QStringLiteral("spinBox_2"));
        spinBox_2->setGeometry(QRect(20, 90, 91, 22));
        spinBox_2->setMaximum(300);
        saveRoom = new QPushButton(page_13);
        saveRoom->setObjectName(QStringLiteral("saveRoom"));
        saveRoom->setGeometry(QRect(10, 120, 113, 32));
        editRoomStackedWidget->addWidget(page_13);
        addRoomStackedWidget = new QStackedWidget(roomsTab);
        addRoomStackedWidget->setObjectName(QStringLiteral("addRoomStackedWidget"));
        addRoomStackedWidget->setGeometry(QRect(200, 290, 171, 161));
        page_16 = new QWidget();
        page_16->setObjectName(QStringLiteral("page_16"));
        addRoomStackedWidget->addWidget(page_16);
        page_17 = new QWidget();
        page_17->setObjectName(QStringLiteral("page_17"));
        label_75 = new QLabel(page_17);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(0, 0, 120, 16));
        label_76 = new QLabel(page_17);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(20, 20, 59, 16));
        roomNumberLineEdit_3 = new QLineEdit(page_17);
        roomNumberLineEdit_3->setObjectName(QStringLiteral("roomNumberLineEdit_3"));
        roomNumberLineEdit_3->setGeometry(QRect(20, 40, 81, 21));
        label_77 = new QLabel(page_17);
        label_77->setObjectName(QStringLiteral("label_77"));
        label_77->setGeometry(QRect(20, 70, 201, 16));
        spinBox_4 = new QSpinBox(page_17);
        spinBox_4->setObjectName(QStringLiteral("spinBox_4"));
        spinBox_4->setGeometry(QRect(20, 90, 91, 22));
        spinBox_4->setMaximum(300);
        saveRoom_3 = new QPushButton(page_17);
        saveRoom_3->setObjectName(QStringLiteral("saveRoom_3"));
        saveRoom_3->setGeometry(QRect(10, 120, 113, 32));
        addRoomStackedWidget->addWidget(page_17);
        addBuildingStackedWidget = new QStackedWidget(roomsTab);
        addBuildingStackedWidget->setObjectName(QStringLiteral("addBuildingStackedWidget"));
        addBuildingStackedWidget->setGeometry(QRect(600, 80, 161, 131));
        page_18 = new QWidget();
        page_18->setObjectName(QStringLiteral("page_18"));
        label_78 = new QLabel(page_18);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(10, 10, 321, 16));
        label_78->setFrameShadow(QFrame::Raised);
        label_78->setTextFormat(Qt::AutoText);
        label_78->setWordWrap(true);
        label_78->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        addBuildingNameLabel = new QLabel(page_18);
        addBuildingNameLabel->setObjectName(QStringLiteral("addBuildingNameLabel"));
        addBuildingNameLabel->setGeometry(QRect(10, 30, 191, 21));
        addBuildingNameLineEdit = new QLineEdit(page_18);
        addBuildingNameLineEdit->setObjectName(QStringLiteral("addBuildingNameLineEdit"));
        addBuildingNameLineEdit->setGeometry(QRect(10, 50, 111, 21));
        saveBuilding_2 = new QPushButton(page_18);
        saveBuilding_2->setObjectName(QStringLiteral("saveBuilding_2"));
        saveBuilding_2->setGeometry(QRect(10, 80, 113, 32));
        addBuildingStackedWidget->addWidget(page_18);
        page_19 = new QWidget();
        page_19->setObjectName(QStringLiteral("page_19"));
        addBuildingStackedWidget->addWidget(page_19);
        editBuildingStackedWidget = new QStackedWidget(roomsTab);
        editBuildingStackedWidget->setObjectName(QStringLiteral("editBuildingStackedWidget"));
        editBuildingStackedWidget->setGeometry(QRect(450, 120, 131, 121));
        page_20 = new QWidget();
        page_20->setObjectName(QStringLiteral("page_20"));
        label_12 = new QLabel(page_20);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(0, 0, 291, 21));
        label_12->setFrameShadow(QFrame::Raised);
        label_12->setTextFormat(Qt::AutoText);
        label_12->setWordWrap(true);
        label_12->setTextInteractionFlags(Qt::LinksAccessibleByMouse);
        label_22 = new QLabel(page_20);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(0, 20, 191, 21));
        editBuildingNameLineEdit = new QLineEdit(page_20);
        editBuildingNameLineEdit->setObjectName(QStringLiteral("editBuildingNameLineEdit"));
        editBuildingNameLineEdit->setGeometry(QRect(0, 40, 121, 21));
        saveBuilding = new QPushButton(page_20);
        saveBuilding->setObjectName(QStringLiteral("saveBuilding"));
        saveBuilding->setGeometry(QRect(0, 70, 121, 32));
        editBuildingStackedWidget->addWidget(page_20);
        page_21 = new QWidget();
        page_21->setObjectName(QStringLiteral("page_21"));
        editBuildingStackedWidget->addWidget(page_21);
        addBuilding = new QPushButton(roomsTab);
        addBuilding->setObjectName(QStringLiteral("addBuilding"));
        addBuilding->setGeometry(QRect(600, 40, 131, 31));
        spinBox_21 = new QSpinBox(roomsTab);
        spinBox_21->setObjectName(QStringLiteral("spinBox_21"));
        spinBox_21->setGeometry(QRect(420, 470, 91, 22));
        roomsTable = new QTableView(roomsTab);
        roomsTable->setObjectName(QStringLiteral("roomsTable"));
        roomsTable->setGeometry(QRect(10, 40, 301, 201));
        roomsTable1 = new QTableView(roomsTab);
        roomsTable1->setObjectName(QStringLiteral("roomsTable1"));
        roomsTable1->setGeometry(QRect(10, 40, 301, 201));
        tabWidget->addTab(roomsTab, QString());
        adminTab = new QWidget();
        adminTab->setObjectName(QStringLiteral("adminTab"));
        studentIDLineEdit = new QLineEdit(adminTab);
        studentIDLineEdit->setObjectName(QStringLiteral("studentIDLineEdit"));
        studentIDLineEdit->setGeometry(QRect(250, 40, 113, 31));
        label_64 = new QLabel(adminTab);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(250, 20, 211, 16));
        findStudentEnter = new QPushButton(adminTab);
        findStudentEnter->setObjectName(QStringLiteral("findStudentEnter"));
        findStudentEnter->setGeometry(QRect(370, 40, 81, 31));
        editOrViewStudent = new QPushButton(adminTab);
        editOrViewStudent->setObjectName(QStringLiteral("editOrViewStudent"));
        editOrViewStudent->setGeometry(QRect(250, 80, 113, 31));
        deleteStudent = new QPushButton(adminTab);
        deleteStudent->setObjectName(QString::fromUtf8("deleteStudent"));
        deleteStudent->setGeometry(QRect(372, 80, 81, 31));
        studentsTable = new QTableView(adminTab);
        studentsTable->setObjectName(QString::fromUtf8("studentsTable"));
        studentsTable->setGeometry(QRect(10, 40, 231, 371));
        addStudent = new QPushButton(adminTab);
        addStudent->setObjectName(QStringLiteral("addStudent"));
        addStudent->setGeometry(QRect(250, 230, 113, 31));
        studentInfoStackedWidget = new QStackedWidget(adminTab);
        studentInfoStackedWidget->setObjectName(QStringLiteral("studentInfoStackedWidget"));
        studentInfoStackedWidget->setGeometry(QRect(470, 20, 451, 501));
        page_11 = new QWidget();
        page_11->setObjectName(QStringLiteral("page_11"));
        studentInfoStackedWidget->addWidget(page_11);
        stackedWidget_2Page1 = new QWidget();
        stackedWidget_2Page1->setObjectName(QStringLiteral("stackedWidget_2Page1"));
        label_65 = new QLabel(stackedWidget_2Page1);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(0, 10, 181, 16));
        studentFirstNameLineEdit = new QLineEdit(stackedWidget_2Page1);
        studentFirstNameLineEdit->setObjectName(QStringLiteral("studentFirstNameLineEdit"));
        studentFirstNameLineEdit->setGeometry(QRect(150, 10, 181, 21));
        label_220 = new QLabel(stackedWidget_2Page1);
        label_220->setObjectName(QStringLiteral("label_220"));
        label_220->setGeometry(QRect(0, 40, 171, 16));
        studentLastNameLineEdit = new QLineEdit(stackedWidget_2Page1);
        studentLastNameLineEdit->setObjectName(QStringLiteral("studentLastNameLineEdit"));
        studentLastNameLineEdit->setGeometry(QRect(150, 40, 181, 21));
        label_230 = new QLabel(stackedWidget_2Page1);
        label_230->setObjectName(QStringLiteral("label_230"));
        label_230->setGeometry(QRect(0, 70, 81, 16));
        studentMILineEdit = new QLineEdit(stackedWidget_2Page1);
        studentMILineEdit->setObjectName(QStringLiteral("studentMILineEdit"));
        studentMILineEdit->setGeometry(QRect(150, 70, 41, 21));
        label_66 = new QLabel(stackedWidget_2Page1);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(0, 110, 81, 16));
        saveStudentData = new QPushButton(stackedWidget_2Page1);
        saveStudentData->setObjectName(QStringLiteral("saveStudentData"));
        saveStudentData->setGeometry(QRect(310, 160, 113, 31));
        widget = new QWidget(stackedWidget_2Page1);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setEnabled(true);
        widget->setGeometry(QRect(-10, 200, 461, 351));
        widget->setAutoFillBackground(false);
        label_160 = new QLabel(widget);
        label_160->setObjectName(QStringLiteral("label_160"));
        label_160->setGeometry(QRect(10, 10, 251, 21));
        omboBox_80 = new QComboBox(widget);
        omboBox_80->setObjectName(QStringLiteral("omboBox_80"));
        omboBox_80->setGeometry(QRect(10, 30, 161, 22));
        label_161 = new QLabel(widget);
        label_161->setObjectName(QString::fromUtf8("label_161"));
        label_161->setGeometry(QRect(20, 110, 91, 16));
        radioButton = new QRadioButton(widget);
        radioButton->setObjectName(QString::fromUtf8("radioButton"));
        radioButton->setGeometry(QRect(130, 110, 141, 21));
        radioButton_2 = new QRadioButton(widget);
        radioButton_2->setObjectName(QString::fromUtf8("radioButton_2"));
        radioButton_2->setGeometry(QRect(210, 110, 91, 21));
        widget_3 = new QWidget(widget);
        widget_3->setObjectName(QStringLiteral("widget_3"));
        widget_3->setGeometry(QRect(10, 140, 451, 191));
        label_67 = new QLabel(widget_3);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(0, 10, 450, 21));
        label_68 = new QLabel(widget_3);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(10, 40, 51, 16));
        studentGradeCourseComboBox = new QComboBox(widget_3);
        studentGradeCourseComboBox->setObjectName(QStringLiteral("studentGradeCourseComboBox"));
        studentGradeCourseComboBox->setGeometry(QRect(10, 60, 161, 22));
        label_200 = new QLabel(widget_3);
        label_200->setObjectName(QStringLiteral("label_200"));
        label_200->setGeometry(QRect(220, 40, 91, 16));
        studentGradeNewGradeComboBox = new QComboBox(widget_3);
        studentGradeNewGradeComboBox->setObjectName(QStringLiteral("studentGradeNewGradeComboBox"));
        studentGradeNewGradeComboBox->setGeometry(QRect(220, 60, 91, 22));
        saveStudentGrade = new QPushButton(widget_3);
        saveStudentGrade->setObjectName(QStringLiteral("saveStudentGrade"));
        saveStudentGrade->setGeometry(QRect(220, 110, 141, 31));
        label_70 = new QLabel(stackedWidget_2Page1);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(10, 170, 81, 21));
        radioButton_3 = new QRadioButton(stackedWidget_2Page1);
        radioButton_3->setObjectName(QStringLiteral("radioButton_3"));
        radioButton_3->setGeometry(QRect(120, 169, 131, 21));
        radioButton_4 = new QRadioButton(stackedWidget_2Page1);
        radioButton_4->setObjectName(QStringLiteral("radioButton_4"));
        radioButton_4->setGeometry(QRect(200, 170, 111, 20));
        semesterEnter = new QPushButton(widget);
        semesterEnter->setObjectName(QString::fromUtf8("semesterEnter"));
        semesterEnter->setGeometry(QRect(170, 70, 61, 21));
        semesterLineEdit = new QLineEdit(widget);
        semesterLineEdit->setObjectName(QString::fromUtf8("semesterLineEdit"));
        semesterLineEdit->setGeometry(QRect(20, 30, 131, 21));
        yearLineEdit = new QLineEdit(widget);
        yearLineEdit->setObjectName(QString::fromUtf8("yearLineEdit"));
        yearLineEdit->setGeometry(QRect(20, 70, 131, 21));
        label_58 = new QLabel(widget);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(10, 50, 251, 20));
        label_72 = new QLabel(stackedWidget_2Page1);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(140, 110, 281, 20));
        studentInfoStackedWidget->addWidget(stackedWidget_2Page1);
        label_23 = new QLabel(adminTab);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(10, 20, 151, 16));
        studentsTable = new QTableView(adminTab);
        studentsTable->setObjectName(QStringLiteral("studentsTable"));
        studentsTable->setGeometry(QRect(10, 40, 231, 511));
        tabWidget->addTab(adminTab, QString());
        superAdminTab = new QWidget();
        superAdminTab->setObjectName(QStringLiteral("superAdminTab"));
        deleteAdmin = new QPushButton(superAdminTab);
        deleteAdmin->setObjectName(QString::fromUtf8("deleteAdmin"));
        deleteAdmin->setGeometry(QRect(330, 40, 141, 21));
        editAdmin = new QPushButton(superAdminTab);
        editAdmin->setObjectName(QString::fromUtf8("editAdmin"));
        editAdmin->setGeometry(QRect(180, 40, 141, 21));
        addAdmin = new QPushButton(superAdminTab);
        addAdmin->setObjectName(QStringLiteral("addAdmin"));
        addAdmin->setEnabled(true);
        addAdmin->setGeometry(QRect(10, 430, 141, 21));
        superAdminLayout = new QWidget(superAdminTab);
        superAdminLayout->setObjectName(QStringLiteral("superAdminLayout"));
        superAdminLayout->setGeometry(QRect(540, 30, 361, 191));
        label_58 = new QLabel(superAdminLayout);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(10, 30, 71, 16));
        label_59 = new QLabel(superAdminLayout);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(10, 80, 71, 21));
        superAdminSave = new QPushButton(superAdminLayout);
        superAdminSave->setObjectName(QStringLiteral("superAdminSave"));
        superAdminSave->setGeometry(QRect(110, 150, 131, 31));
        label_60 = new QLabel(superAdminLayout);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(100, 80, 181, 21));
        superAdminPasswordLineEdit = new QLineEdit(superAdminLayout);
        superAdminPasswordLineEdit->setObjectName(QStringLiteral("superAdminPasswordLineEdit"));
        superAdminPasswordLineEdit->setGeometry(QRect(100, 30, 181, 21));
        label_71 = new QLabel(superAdminTab);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(10, 20, 59, 16));
        editAdminStackedWidget = new QStackedWidget(superAdminTab);
        editAdminStackedWidget->setObjectName(QString::fromUtf8("editAdminStackedWidget"));
        editAdminStackedWidget->setGeometry(QRect(180, 70, 141, 151));
        page_7 = new QWidget();
        page_7->setObjectName(QStringLiteral("page_7"));
        editAdminStackedWidget->addWidget(page_7);
        page_8 = new QWidget();
        page_8->setObjectName(QStringLiteral("page_8"));
        adminNewNameLabel = new QLabel(page_8);
        adminNewNameLabel->setObjectName(QString::fromUtf8("adminNewNameLabel"));
        adminNewNameLabel->setGeometry(QRect(0, 60, 141, 21));
        editAdminPasswordLineEdit = new QLineEdit(page_8);
        editAdminPasswordLineEdit->setObjectName(QString::fromUtf8("editAdminPasswordLineEdit"));
        editAdminPasswordLineEdit->setGeometry(QRect(0, 80, 121, 21));
        editAdminEnterPushButton = new QPushButton(page_8);
        editAdminEnterPushButton->setObjectName(QString::fromUtf8("editAdminEnterPushButton"));
        editAdminEnterPushButton->setGeometry(QRect(70, 110, 56, 21));
        label_25 = new QLabel(page_8);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(0, 10, 171, 16));
        editAdminIDLineEdit = new QLineEdit(page_8);
        editAdminIDLineEdit->setObjectName(QString::fromUtf8("editAdminIDLineEdit"));
        editAdminIDLineEdit->setGeometry(QRect(0, 30, 121, 21));
        editAdminStackedWidget->addWidget(page_8);
        addAdminStackedWidget = new QStackedWidget(superAdminTab);
        addAdminStackedWidget->setObjectName(QString::fromUtf8("addAdminStackedWidget"));
        addAdminStackedWidget->setGeometry(QRect(10, 70, 141, 91));
        page_9 = new QWidget();
        page_9->setObjectName(QStringLiteral("page_9"));
        addAdminStackedWidget->addWidget(page_9);
        page_10 = new QWidget();
        page_10->setObjectName(QStringLiteral("page_10"));
        adminNameLabel = new QLabel(page_10);
        adminNameLabel->setObjectName(QStringLiteral("adminNameLabel"));
        adminNameLabel->setEnabled(true);
        adminNameLabel->setGeometry(QRect(10, 10, 119, 21));
        newAdminLineEdit = new QLineEdit(page_10);
        newAdminLineEdit->setObjectName(QStringLiteral("newAdminLineEdit"));
        newAdminLineEdit->setGeometry(QRect(10, 30, 119, 22));
        addAdminEnterPushButton = new QPushButton(page_10);
        addAdminEnterPushButton->setObjectName(QStringLiteral("addAdminEnterPushButton"));
        addAdminEnterPushButton->setGeometry(QRect(70, 60, 56, 21));
        addAdminStackedWidget->addWidget(page_10);
        deleteAdminStackedWidget = new QStackedWidget(superAdminTab);
        deleteAdminStackedWidget->setObjectName(QString::fromUtf8("deleteAdminStackedWidget"));
        deleteAdminStackedWidget->setGeometry(QRect(330, 70, 141, 91));
        page_14 = new QWidget();
        page_14->setObjectName(QString::fromUtf8("page_14"));
        deleteAdminStackedWidget->addWidget(page_14);
        page_15 = new QWidget();
        page_15->setObjectName(QString::fromUtf8("page_15"));
        deleteAdminIDLabel = new QLabel(page_15);
        deleteAdminIDLabel->setObjectName(QString::fromUtf8("deleteAdminIDLabel"));
        deleteAdminIDLabel->setEnabled(true);
        deleteAdminIDLabel->setGeometry(QRect(10, 10, 119, 21));
        deleteAdminLineEdit = new QLineEdit(page_15);
        deleteAdminLineEdit->setObjectName(QString::fromUtf8("deleteAdminLineEdit"));
        deleteAdminLineEdit->setGeometry(QRect(10, 30, 119, 22));
        deleteAdminEnterPushButton = new QPushButton(page_15);
        deleteAdminEnterPushButton->setObjectName(QString::fromUtf8("deleteAdminEnterPushButton"));
        deleteAdminEnterPushButton->setGeometry(QRect(70, 60, 56, 21));
        deleteAdminStackedWidget->addWidget(page_15);
        tabWidget->addTab(superAdminTab, QString());
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1028, 20));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(5);
        stackedWidget->setCurrentIndex(5);
        editRoomStackedWidget->setCurrentIndex(0);
        addRoomStackedWidget->setCurrentIndex(0);
        addBuildingStackedWidget->setCurrentIndex(1);
        editBuildingStackedWidget->setCurrentIndex(1);
        studentInfoStackedWidget->setCurrentIndex(0);
        studentGradeNewGradeComboBox->setCurrentIndex(0);
        editAdminStackedWidget->setCurrentIndex(0);
        addAdminStackedWidget->setCurrentIndex(0);
        deleteAdminStackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        label->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Major:", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Course:", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "Add Class", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "Remove Class", nullptr));
        pushButton_4->setText(QApplication::translate("MainWindow", "Remove", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "Current Schedule:", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "First Name:", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "Last Name:", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "Middle Initial:", nullptr));
        label_61->setText(QApplication::translate("MainWindow", "AdminID:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Student", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "College:", nullptr));
        pushButton_5->setText(QApplication::translate("MainWindow", "Add", nullptr));
        pushButton_6->setText(QApplication::translate("MainWindow", "Edit", nullptr));
        pushButton_7->setText(QApplication::translate("MainWindow", "Remove", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "Major", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "Course", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "Sections", nullptr));
        label_27->setText(QApplication::translate("MainWindow", "Add or Edit College", nullptr));
        label_28->setText(QApplication::translate("MainWindow", "College Name:", nullptr));
        pushButton_19->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_29->setText(QApplication::translate("MainWindow", "Add or Edit Department", nullptr));
        label_30->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_31->setText(QApplication::translate("MainWindow", "Department Name:", nullptr));
        pushButton_20->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_36->setText(QApplication::translate("MainWindow", "Department Head:", nullptr));
        label_32->setText(QApplication::translate("MainWindow", "Add or Edit Major", nullptr));
        label_33->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_34->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_35->setText(QApplication::translate("MainWindow", "Major Name:", nullptr));
        pushButton_21->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_37->setText(QApplication::translate("MainWindow", "Add or Edit Course", nullptr));
        label_38->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_39->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_40->setText(QApplication::translate("MainWindow", "Major", nullptr));
        label_41->setText(QApplication::translate("MainWindow", "Course Name:", nullptr));
        pushButton_22->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_42->setText(QApplication::translate("MainWindow", "Add or Edit Section", nullptr));
        label_43->setText(QApplication::translate("MainWindow", "College:", nullptr));
        label_44->setText(QApplication::translate("MainWindow", "Department:", nullptr));
        label_45->setText(QApplication::translate("MainWindow", "Major:", nullptr));
        label_46->setText(QApplication::translate("MainWindow", "Course:", nullptr));
        label_47->setText(QApplication::translate("MainWindow", "Section #:", nullptr));
        label_48->setText(QApplication::translate("MainWindow", "Professor:", nullptr));
        pushButton_23->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_54->setText(QApplication::translate("MainWindow", "Start Time:", nullptr));
        label_55->setText(QApplication::translate("MainWindow", "End Time:", nullptr));
        label_56->setText(QApplication::translate("MainWindow", "Year:", nullptr));
        label_57->setText(QApplication::translate("MainWindow", "Semester:", nullptr));
        label_62->setText(QApplication::translate("MainWindow", "Building:", nullptr));
        label_63->setText(QApplication::translate("MainWindow", "Room #:", nullptr));
        pushButton_15->setText(QApplication::translate("MainWindow", "Add", nullptr));
        pushButton_16->setText(QApplication::translate("MainWindow", "Add", nullptr));
        pushButton_17->setText(QApplication::translate("MainWindow", "Add", nullptr));
        pushButton_18->setText(QApplication::translate("MainWindow", "Add", nullptr));
        label_52->setText(QApplication::translate("MainWindow", "Year:", nullptr));
        label_53->setText(QApplication::translate("MainWindow", "Semester:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "University", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "Employee List:", nullptr));
        pushButton_8->setText(QApplication::translate("MainWindow", "Add", nullptr));
        pushButton_9->setText(QApplication::translate("MainWindow", "Edit", nullptr));
        pushButton_10->setText(QApplication::translate("MainWindow", "Delete", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "First Name", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "Last Name", nullptr));
        label_49->setText(QApplication::translate("MainWindow", "MI:", nullptr));
        label_50->setText(QApplication::translate("MainWindow", "Employee Title:", nullptr));
        label_51->setText(QApplication::translate("MainWindow", "Salary:", nullptr));
        pushButton_24->setText(QApplication::translate("MainWindow", "Save", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_9), QApplication::translate("MainWindow", "Employees", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "Select a Building to see Rooms", nullptr));
        deleteRoom->setText(QApplication::translate("MainWindow", " Delete Room", nullptr));
        editRoom->setText(QApplication::translate("MainWindow", "Edit Room", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "Rooms:", nullptr));
        deleteBuilding->setText(QApplication::translate("MainWindow", "Delete Building", nullptr));
        editBuilding->setText(QApplication::translate("MainWindow", "Edit Building", nullptr));
        pushButton->setText(QApplication::translate("MainWindow", "Add Room", nullptr));
        label_24->setText(QApplication::translate("MainWindow", "Edit Room", nullptr));
        label_26->setText(QApplication::translate("MainWindow", "Room #:", nullptr));
        label_69->setText(QApplication::translate("MainWindow", "Room Occupancy:", nullptr));
        saveRoom->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_75->setText(QApplication::translate("MainWindow", "Add Room", nullptr));
        label_76->setText(QApplication::translate("MainWindow", "Room #:", nullptr));
        label_77->setText(QApplication::translate("MainWindow", "Room Occupancy:", nullptr));
        saveRoom_3->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_78->setText(QApplication::translate("MainWindow", "Add/Edit Building", nullptr));
        addBuildingNameLabel->setText(QApplication::translate("MainWindow", "Building Name:", nullptr));
        saveBuilding_2->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "Edit Building", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "Building Name:", nullptr));
        saveBuilding->setText(QApplication::translate("MainWindow", "Save", nullptr));
        addBuilding->setText(QApplication::translate("MainWindow", "Add Building", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(roomsTab), QApplication::translate("MainWindow", "Rooms", nullptr));
        label_64->setText(QApplication::translate("MainWindow", "Find Student by ID:", nullptr));
        findStudentEnter->setText(QApplication::translate("MainWindow", "Enter", nullptr));
        deleteStudent->setText(QApplication::translate("MainWindow", "Delete", nullptr));
        addStudent->setText(QApplication::translate("MainWindow", "Add Student", nullptr));
        label_65->setText(QApplication::translate("MainWindow", "Student First Name:", nullptr));
        label_220->setText(QApplication::translate("MainWindow", "Student Last Name:", nullptr));
        label_230->setText(QApplication::translate("MainWindow", "Student MI:", nullptr));
        label_66->setText(QApplication::translate("MainWindow", "Student ID:", nullptr));
        saveStudentData->setText(QApplication::translate("MainWindow", "Save", nullptr));
        label_160->setText(QApplication::translate("MainWindow", "Pick Semester you want to view:", nullptr));
        label_161->setText(QApplication::translate("MainWindow", "Paid Tuition:", nullptr));
        radioButton->setText(QApplication::translate("MainWindow", "Yes", nullptr));
        radioButton_2->setText(QApplication::translate("MainWindow", "No", nullptr));
        label_67->setText(QApplication::translate("MainWindow", "Edit Student Grade for a Course in Semester picked above:", nullptr));
        label_68->setText(QApplication::translate("MainWindow", "Course: ", nullptr));
        label_200->setText(QApplication::translate("MainWindow", "New Grade:", nullptr));
        studentGradeNewGradeComboBox->setItemText(0, QApplication::translate("MainWindow", "A", nullptr));
        studentGradeNewGradeComboBox->setItemText(1, QApplication::translate("MainWindow", "B", nullptr));
        studentGradeNewGradeComboBox->setItemText(2, QApplication::translate("MainWindow", "C", nullptr));
        studentGradeNewGradeComboBox->setItemText(3, QApplication::translate("MainWindow", "D", nullptr));
        studentGradeNewGradeComboBox->setItemText(4, QApplication::translate("MainWindow", "F", nullptr));

        studentGradeNewGradeComboBox->setCurrentText(QApplication::translate("MainWindow", "A", nullptr));
        saveStudentGrade->setText(QApplication::translate("MainWindow", "Save", nullptr));
        semesterEnter->setText(QApplication::translate("MainWindow", "Enter", nullptr));
        label_58->setText(QApplication::translate("MainWindow", "Pick Year you want to view:", nullptr));
        label_72->setText(QApplication::translate("MainWindow", "ID# (placeholder)", nullptr));
        label_23->setText(QApplication::translate("MainWindow", "Students:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(adminTab), QApplication::translate("MainWindow", "Admin", nullptr));
        deleteAdmin->setText(QApplication::translate("MainWindow", "Delete Admin", nullptr));
        editAdmin->setText(QApplication::translate("MainWindow", "Edit Admin", nullptr));
        addAdmin->setText(QApplication::translate("MainWindow", "Add Admin", nullptr));
        label_71->setText(QApplication::translate("MainWindow", "Admins:", nullptr));
        adminNewNameLabel->setText(QApplication::translate("MainWindow", "Admin New Password:", nullptr));
        editAdminEnterPushButton->setText(QApplication::translate("MainWindow", "Enter", nullptr));
        label_25->setText(QApplication::translate("MainWindow", "Admin ID:", nullptr));
        adminNameLabel->setText(QApplication::translate("MainWindow", "Admin Password:", nullptr));
        addAdminEnterPushButton->setText(QApplication::translate("MainWindow", "Enter", nullptr));
        deleteAdminIDLabel->setText(QApplication::translate("MainWindow", "Admin ID:", nullptr));
        deleteAdminEnterPushButton->setText(QApplication::translate("MainWindow", "Enter", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(superAdminTab), QApplication::translate("MainWindow", "Super Admin", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
